// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Enum.proto
// Protobuf C++ Version: 5.29.5

#ifndef Enum_2eproto_2epb_2eh
#define Enum_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Enum_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Protocol {
enum PacketType : int {
  NONE_TYPE = 0,
  CS_LOGIN = 1,
  CS_INPUT = 2,
  SC_LOGIN = 3,
  SC_ADD = 4,
  SC_MOVE_OBJECT = 5,
  SC_REMOVE = 6,
  SC_ATTACK = 7,
  SC_DODGE = 8,
  PacketType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  PacketType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool PacketType_IsValid(int value);
extern const uint32_t PacketType_internal_data_[];
constexpr PacketType PacketType_MIN = static_cast<PacketType>(0);
constexpr PacketType PacketType_MAX = static_cast<PacketType>(8);
constexpr int PacketType_ARRAYSIZE = 8 + 1;
const ::google::protobuf::EnumDescriptor*
PacketType_descriptor();
template <typename T>
const std::string& PacketType_Name(T value) {
  static_assert(std::is_same<T, PacketType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PacketType_Name().");
  return PacketType_Name(static_cast<PacketType>(value));
}
template <>
inline const std::string& PacketType_Name(PacketType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PacketType_descriptor,
                                                 0, 8>(
      static_cast<int>(value));
}
inline bool PacketType_Parse(absl::string_view name, PacketType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PacketType>(
      PacketType_descriptor(), name, value);
}
enum Input : int {
  NONE_INPUT = 0,
  MOVE = 1,
  ATTACK = 2,
  DODGE = 3,
  Input_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  Input_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool Input_IsValid(int value);
extern const uint32_t Input_internal_data_[];
constexpr Input Input_MIN = static_cast<Input>(0);
constexpr Input Input_MAX = static_cast<Input>(3);
constexpr int Input_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
Input_descriptor();
template <typename T>
const std::string& Input_Name(T value) {
  static_assert(std::is_same<T, Input>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to Input_Name().");
  return Input_Name(static_cast<Input>(value));
}
template <>
inline const std::string& Input_Name(Input value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Input_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool Input_Parse(absl::string_view name, Input* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Input>(
      Input_descriptor(), name, value);
}
enum InputType : int {
  NONE_INPUT_TYPE = 0,
  KeyDown = 1,
  KeyUp = 2,
  InputType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  InputType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool InputType_IsValid(int value);
extern const uint32_t InputType_internal_data_[];
constexpr InputType InputType_MIN = static_cast<InputType>(0);
constexpr InputType InputType_MAX = static_cast<InputType>(2);
constexpr int InputType_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
InputType_descriptor();
template <typename T>
const std::string& InputType_Name(T value) {
  static_assert(std::is_same<T, InputType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to InputType_Name().");
  return InputType_Name(static_cast<InputType>(value));
}
template <>
inline const std::string& InputType_Name(InputType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<InputType_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool InputType_Parse(absl::string_view name, InputType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<InputType>(
      InputType_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Protocol::PacketType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::PacketType>() {
  return ::Protocol::PacketType_descriptor();
}
template <>
struct is_proto_enum<::Protocol::Input> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::Input>() {
  return ::Protocol::Input_descriptor();
}
template <>
struct is_proto_enum<::Protocol::InputType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::InputType>() {
  return ::Protocol::InputType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Enum_2eproto_2epb_2eh
