// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Protocol.proto
// Protobuf C++ Version: 5.29.5

#include "Protocol.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Protocol {
              template <typename>
PROTOBUF_CONSTEXPR SC_REMOVE_PACKET::SC_REMOVE_PACKET(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct SC_REMOVE_PACKETDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_REMOVE_PACKETDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_REMOVE_PACKETDefaultTypeInternal() {}
  union {
    SC_REMOVE_PACKET _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_REMOVE_PACKETDefaultTypeInternal _SC_REMOVE_PACKET_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR SC_LOGIN_PACKET::SC_LOGIN_PACKET(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct SC_LOGIN_PACKETDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_LOGIN_PACKETDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_LOGIN_PACKETDefaultTypeInternal() {}
  union {
    SC_LOGIN_PACKET _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_LOGIN_PACKETDefaultTypeInternal _SC_LOGIN_PACKET_default_instance_;

inline constexpr SC_ATTACK_PACKET::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : rot_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SC_ATTACK_PACKET::SC_ATTACK_PACKET(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SC_ATTACK_PACKETDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_ATTACK_PACKETDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_ATTACK_PACKETDefaultTypeInternal() {}
  union {
    SC_ATTACK_PACKET _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_ATTACK_PACKETDefaultTypeInternal _SC_ATTACK_PACKET_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR CS_LOGIN_PACKET::CS_LOGIN_PACKET(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct CS_LOGIN_PACKETDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_LOGIN_PACKETDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_LOGIN_PACKETDefaultTypeInternal() {}
  union {
    CS_LOGIN_PACKET _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_LOGIN_PACKETDefaultTypeInternal _CS_LOGIN_PACKET_default_instance_;

inline constexpr SC_MOVE_PACKET::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pos_{nullptr},
        rot_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SC_MOVE_PACKET::SC_MOVE_PACKET(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SC_MOVE_PACKETDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_MOVE_PACKETDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_MOVE_PACKETDefaultTypeInternal() {}
  union {
    SC_MOVE_PACKET _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_MOVE_PACKETDefaultTypeInternal _SC_MOVE_PACKET_default_instance_;

inline constexpr SC_DODGE_PACKET::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        dir_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR SC_DODGE_PACKET::SC_DODGE_PACKET(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SC_DODGE_PACKETDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_DODGE_PACKETDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_DODGE_PACKETDefaultTypeInternal() {}
  union {
    SC_DODGE_PACKET _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_DODGE_PACKETDefaultTypeInternal _SC_DODGE_PACKET_default_instance_;

inline constexpr SC_ADD_PACKET::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pos_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR SC_ADD_PACKET::SC_ADD_PACKET(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SC_ADD_PACKETDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_ADD_PACKETDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_ADD_PACKETDefaultTypeInternal() {}
  union {
    SC_ADD_PACKET _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_ADD_PACKETDefaultTypeInternal _SC_ADD_PACKET_default_instance_;

inline constexpr GamePacket::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        body_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        header_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR GamePacket::GamePacket(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GamePacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GamePacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GamePacketDefaultTypeInternal() {}
  union {
    GamePacket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GamePacketDefaultTypeInternal _GamePacket_default_instance_;

inline constexpr CS_INPUT_PACKET::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        payload_{nullptr},
        key_{static_cast< ::Protocol::Input >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR CS_INPUT_PACKET::CS_INPUT_PACKET(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CS_INPUT_PACKETDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_INPUT_PACKETDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_INPUT_PACKETDefaultTypeInternal() {}
  union {
    CS_INPUT_PACKET _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_INPUT_PACKETDefaultTypeInternal _CS_INPUT_PACKET_default_instance_;
}  // namespace Protocol
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Protocol_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Protocol_2eproto = nullptr;
const ::uint32_t
    TableStruct_Protocol_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::Protocol::GamePacket, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Protocol::GamePacket, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::GamePacket, _impl_.header_),
        PROTOBUF_FIELD_OFFSET(::Protocol::GamePacket, _impl_.body_),
        0,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::CS_LOGIN_PACKET, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::CS_INPUT_PACKET, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Protocol::CS_INPUT_PACKET, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::CS_INPUT_PACKET, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::Protocol::CS_INPUT_PACKET, _impl_.payload_),
        ~0u,
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_LOGIN_PACKET, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_ADD_PACKET, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_ADD_PACKET, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_ADD_PACKET, _impl_.pos_),
        0,
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_MOVE_PACKET, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_MOVE_PACKET, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_MOVE_PACKET, _impl_.pos_),
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_MOVE_PACKET, _impl_.rot_),
        0,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_REMOVE_PACKET, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_ATTACK_PACKET, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_ATTACK_PACKET, _impl_.rot_),
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_DODGE_PACKET, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_DODGE_PACKET, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_DODGE_PACKET, _impl_.dir_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::Protocol::GamePacket)},
        {12, -1, -1, sizeof(::Protocol::CS_LOGIN_PACKET)},
        {20, 30, -1, sizeof(::Protocol::CS_INPUT_PACKET)},
        {32, -1, -1, sizeof(::Protocol::SC_LOGIN_PACKET)},
        {40, 49, -1, sizeof(::Protocol::SC_ADD_PACKET)},
        {50, 60, -1, sizeof(::Protocol::SC_MOVE_PACKET)},
        {62, -1, -1, sizeof(::Protocol::SC_REMOVE_PACKET)},
        {70, -1, -1, sizeof(::Protocol::SC_ATTACK_PACKET)},
        {79, 88, -1, sizeof(::Protocol::SC_DODGE_PACKET)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::Protocol::_GamePacket_default_instance_._instance,
    &::Protocol::_CS_LOGIN_PACKET_default_instance_._instance,
    &::Protocol::_CS_INPUT_PACKET_default_instance_._instance,
    &::Protocol::_SC_LOGIN_PACKET_default_instance_._instance,
    &::Protocol::_SC_ADD_PACKET_default_instance_._instance,
    &::Protocol::_SC_MOVE_PACKET_default_instance_._instance,
    &::Protocol::_SC_REMOVE_PACKET_default_instance_._instance,
    &::Protocol::_SC_ATTACK_PACKET_default_instance_._instance,
    &::Protocol::_SC_DODGE_PACKET_default_instance_._instance,
};
const char descriptor_table_protodef_Protocol_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016Protocol.proto\022\010Protocol\032\nEnum.proto\032\014"
    "Struct.proto\"B\n\nGamePacket\022&\n\006header\030\001 \001"
    "(\0132\026.Protocol.PacketHeader\022\014\n\004body\030\002 \001(\014"
    "\"\021\n\017CS_LOGIN_PACKET\"X\n\017CS_INPUT_PACKET\022\034"
    "\n\003key\030\001 \001(\0162\017.Protocol.Input\022\'\n\007payload\030"
    "\002 \001(\0132\026.Protocol.InputPayload\"\021\n\017SC_LOGI"
    "N_PACKET\",\n\rSC_ADD_PACKET\022\033\n\003pos\030\001 \001(\0132\016"
    ".Protocol.Vec3\":\n\016SC_MOVE_PACKET\022\033\n\003pos\030"
    "\001 \001(\0132\016.Protocol.Vec3\022\013\n\003rot\030\002 \001(\002\"\022\n\020SC"
    "_REMOVE_PACKET\"\037\n\020SC_ATTACK_PACKET\022\013\n\003ro"
    "t\030\001 \001(\002\".\n\017SC_DODGE_PACKET\022\033\n\003dir\030\001 \001(\0132"
    "\016.Protocol.Vec3b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_Protocol_2eproto_deps[2] =
    {
        &::descriptor_table_Enum_2eproto,
        &::descriptor_table_Struct_2eproto,
};
static ::absl::once_flag descriptor_table_Protocol_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Protocol_2eproto = {
    false,
    false,
    463,
    descriptor_table_protodef_Protocol_2eproto,
    "Protocol.proto",
    &descriptor_table_Protocol_2eproto_once,
    descriptor_table_Protocol_2eproto_deps,
    2,
    9,
    schemas,
    file_default_instances,
    TableStruct_Protocol_2eproto::offsets,
    file_level_enum_descriptors_Protocol_2eproto,
    file_level_service_descriptors_Protocol_2eproto,
};
namespace Protocol {
// ===================================================================

class GamePacket::_Internal {
 public:
  using HasBits =
      decltype(std::declval<GamePacket>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GamePacket, _impl_._has_bits_);
};

void GamePacket::clear_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.header_ != nullptr) _impl_.header_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
GamePacket::GamePacket(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.GamePacket)
}
inline PROTOBUF_NDEBUG_INLINE GamePacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Protocol::GamePacket& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        body_(arena, from.body_) {}

GamePacket::GamePacket(
    ::google::protobuf::Arena* arena,
    const GamePacket& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GamePacket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.header_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::Protocol::PacketHeader>(
                              arena, *from._impl_.header_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:Protocol.GamePacket)
}
inline PROTOBUF_NDEBUG_INLINE GamePacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        body_(arena) {}

inline void GamePacket::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.header_ = {};
}
GamePacket::~GamePacket() {
  // @@protoc_insertion_point(destructor:Protocol.GamePacket)
  SharedDtor(*this);
}
inline void GamePacket::SharedDtor(MessageLite& self) {
  GamePacket& this_ = static_cast<GamePacket&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.body_.Destroy();
  delete this_._impl_.header_;
  this_._impl_.~Impl_();
}

inline void* GamePacket::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GamePacket(arena);
}
constexpr auto GamePacket::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GamePacket),
                                            alignof(GamePacket));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GamePacket::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GamePacket_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GamePacket::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GamePacket>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GamePacket::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GamePacket>(), &GamePacket::ByteSizeLong,
            &GamePacket::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GamePacket, _impl_._cached_size_),
        false,
    },
    &GamePacket::kDescriptorMethods,
    &descriptor_table_Protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GamePacket::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> GamePacket::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GamePacket, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::GamePacket>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes body = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(GamePacket, _impl_.body_)}},
    // .Protocol.PacketHeader header = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(GamePacket, _impl_.header_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Protocol.PacketHeader header = 1;
    {PROTOBUF_FIELD_OFFSET(GamePacket, _impl_.header_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bytes body = 2;
    {PROTOBUF_FIELD_OFFSET(GamePacket, _impl_.body_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Protocol::PacketHeader>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void GamePacket::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.GamePacket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.body_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.header_ != nullptr);
    _impl_.header_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GamePacket::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GamePacket& this_ = static_cast<const GamePacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GamePacket::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GamePacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.GamePacket)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .Protocol.PacketHeader header = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.header_, this_._impl_.header_->GetCachedSize(), target,
                stream);
          }

          // bytes body = 2;
          if (!this_._internal_body().empty()) {
            const std::string& _s = this_._internal_body();
            target = stream->WriteBytesMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.GamePacket)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GamePacket::ByteSizeLong(const MessageLite& base) {
          const GamePacket& this_ = static_cast<const GamePacket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GamePacket::ByteSizeLong() const {
          const GamePacket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.GamePacket)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bytes body = 2;
            if (!this_._internal_body().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_body());
            }
          }
           {
            // .Protocol.PacketHeader header = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.header_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GamePacket::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GamePacket*>(&to_msg);
  auto& from = static_cast<const GamePacket&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.GamePacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_body().empty()) {
    _this->_internal_set_body(from._internal_body());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.header_ != nullptr);
    if (_this->_impl_.header_ == nullptr) {
      _this->_impl_.header_ =
          ::google::protobuf::Message::CopyConstruct<::Protocol::PacketHeader>(arena, *from._impl_.header_);
    } else {
      _this->_impl_.header_->MergeFrom(*from._impl_.header_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GamePacket::CopyFrom(const GamePacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.GamePacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GamePacket::InternalSwap(GamePacket* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.body_, &other->_impl_.body_, arena);
  swap(_impl_.header_, other->_impl_.header_);
}

::google::protobuf::Metadata GamePacket::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CS_LOGIN_PACKET::_Internal {
 public:
};

CS_LOGIN_PACKET::CS_LOGIN_PACKET(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:Protocol.CS_LOGIN_PACKET)
}
CS_LOGIN_PACKET::CS_LOGIN_PACKET(
    ::google::protobuf::Arena* arena,
    const CS_LOGIN_PACKET& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CS_LOGIN_PACKET* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Protocol.CS_LOGIN_PACKET)
}

inline void* CS_LOGIN_PACKET::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CS_LOGIN_PACKET(arena);
}
constexpr auto CS_LOGIN_PACKET::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CS_LOGIN_PACKET),
                                            alignof(CS_LOGIN_PACKET));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CS_LOGIN_PACKET::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CS_LOGIN_PACKET_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CS_LOGIN_PACKET::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<CS_LOGIN_PACKET>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CS_LOGIN_PACKET::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<CS_LOGIN_PACKET>(), &CS_LOGIN_PACKET::ByteSizeLong,
            &CS_LOGIN_PACKET::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CS_LOGIN_PACKET, _impl_._cached_size_),
        false,
    },
    &CS_LOGIN_PACKET::kDescriptorMethods,
    &descriptor_table_Protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CS_LOGIN_PACKET::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> CS_LOGIN_PACKET::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::CS_LOGIN_PACKET>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata CS_LOGIN_PACKET::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CS_INPUT_PACKET::_Internal {
 public:
  using HasBits =
      decltype(std::declval<CS_INPUT_PACKET>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CS_INPUT_PACKET, _impl_._has_bits_);
};

void CS_INPUT_PACKET::clear_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.payload_ != nullptr) _impl_.payload_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
CS_INPUT_PACKET::CS_INPUT_PACKET(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.CS_INPUT_PACKET)
}
inline PROTOBUF_NDEBUG_INLINE CS_INPUT_PACKET::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Protocol::CS_INPUT_PACKET& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

CS_INPUT_PACKET::CS_INPUT_PACKET(
    ::google::protobuf::Arena* arena,
    const CS_INPUT_PACKET& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CS_INPUT_PACKET* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.payload_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::Protocol::InputPayload>(
                              arena, *from._impl_.payload_)
                        : nullptr;
  _impl_.key_ = from._impl_.key_;

  // @@protoc_insertion_point(copy_constructor:Protocol.CS_INPUT_PACKET)
}
inline PROTOBUF_NDEBUG_INLINE CS_INPUT_PACKET::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CS_INPUT_PACKET::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, payload_),
           0,
           offsetof(Impl_, key_) -
               offsetof(Impl_, payload_) +
               sizeof(Impl_::key_));
}
CS_INPUT_PACKET::~CS_INPUT_PACKET() {
  // @@protoc_insertion_point(destructor:Protocol.CS_INPUT_PACKET)
  SharedDtor(*this);
}
inline void CS_INPUT_PACKET::SharedDtor(MessageLite& self) {
  CS_INPUT_PACKET& this_ = static_cast<CS_INPUT_PACKET&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.payload_;
  this_._impl_.~Impl_();
}

inline void* CS_INPUT_PACKET::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CS_INPUT_PACKET(arena);
}
constexpr auto CS_INPUT_PACKET::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CS_INPUT_PACKET),
                                            alignof(CS_INPUT_PACKET));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CS_INPUT_PACKET::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CS_INPUT_PACKET_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CS_INPUT_PACKET::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CS_INPUT_PACKET>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CS_INPUT_PACKET::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CS_INPUT_PACKET>(), &CS_INPUT_PACKET::ByteSizeLong,
            &CS_INPUT_PACKET::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CS_INPUT_PACKET, _impl_._cached_size_),
        false,
    },
    &CS_INPUT_PACKET::kDescriptorMethods,
    &descriptor_table_Protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CS_INPUT_PACKET::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> CS_INPUT_PACKET::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CS_INPUT_PACKET, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::CS_INPUT_PACKET>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .Protocol.InputPayload payload = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(CS_INPUT_PACKET, _impl_.payload_)}},
    // .Protocol.Input key = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CS_INPUT_PACKET, _impl_.key_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CS_INPUT_PACKET, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Protocol.Input key = 1;
    {PROTOBUF_FIELD_OFFSET(CS_INPUT_PACKET, _impl_.key_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // .Protocol.InputPayload payload = 2;
    {PROTOBUF_FIELD_OFFSET(CS_INPUT_PACKET, _impl_.payload_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Protocol::InputPayload>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void CS_INPUT_PACKET::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.CS_INPUT_PACKET)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.payload_ != nullptr);
    _impl_.payload_->Clear();
  }
  _impl_.key_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CS_INPUT_PACKET::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CS_INPUT_PACKET& this_ = static_cast<const CS_INPUT_PACKET&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CS_INPUT_PACKET::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CS_INPUT_PACKET& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.CS_INPUT_PACKET)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .Protocol.Input key = 1;
          if (this_._internal_key() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_key(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .Protocol.InputPayload payload = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.payload_, this_._impl_.payload_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.CS_INPUT_PACKET)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CS_INPUT_PACKET::ByteSizeLong(const MessageLite& base) {
          const CS_INPUT_PACKET& this_ = static_cast<const CS_INPUT_PACKET&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CS_INPUT_PACKET::ByteSizeLong() const {
          const CS_INPUT_PACKET& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.CS_INPUT_PACKET)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .Protocol.InputPayload payload = 2;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_);
            }
          }
           {
            // .Protocol.Input key = 1;
            if (this_._internal_key() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_key());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CS_INPUT_PACKET::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CS_INPUT_PACKET*>(&to_msg);
  auto& from = static_cast<const CS_INPUT_PACKET&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.CS_INPUT_PACKET)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.payload_ != nullptr);
    if (_this->_impl_.payload_ == nullptr) {
      _this->_impl_.payload_ =
          ::google::protobuf::Message::CopyConstruct<::Protocol::InputPayload>(arena, *from._impl_.payload_);
    } else {
      _this->_impl_.payload_->MergeFrom(*from._impl_.payload_);
    }
  }
  if (from._internal_key() != 0) {
    _this->_impl_.key_ = from._impl_.key_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CS_INPUT_PACKET::CopyFrom(const CS_INPUT_PACKET& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.CS_INPUT_PACKET)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CS_INPUT_PACKET::InternalSwap(CS_INPUT_PACKET* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CS_INPUT_PACKET, _impl_.key_)
      + sizeof(CS_INPUT_PACKET::_impl_.key_)
      - PROTOBUF_FIELD_OFFSET(CS_INPUT_PACKET, _impl_.payload_)>(
          reinterpret_cast<char*>(&_impl_.payload_),
          reinterpret_cast<char*>(&other->_impl_.payload_));
}

::google::protobuf::Metadata CS_INPUT_PACKET::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SC_LOGIN_PACKET::_Internal {
 public:
};

SC_LOGIN_PACKET::SC_LOGIN_PACKET(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:Protocol.SC_LOGIN_PACKET)
}
SC_LOGIN_PACKET::SC_LOGIN_PACKET(
    ::google::protobuf::Arena* arena,
    const SC_LOGIN_PACKET& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SC_LOGIN_PACKET* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Protocol.SC_LOGIN_PACKET)
}

inline void* SC_LOGIN_PACKET::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SC_LOGIN_PACKET(arena);
}
constexpr auto SC_LOGIN_PACKET::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SC_LOGIN_PACKET),
                                            alignof(SC_LOGIN_PACKET));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SC_LOGIN_PACKET::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SC_LOGIN_PACKET_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SC_LOGIN_PACKET::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<SC_LOGIN_PACKET>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SC_LOGIN_PACKET::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<SC_LOGIN_PACKET>(), &SC_LOGIN_PACKET::ByteSizeLong,
            &SC_LOGIN_PACKET::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SC_LOGIN_PACKET, _impl_._cached_size_),
        false,
    },
    &SC_LOGIN_PACKET::kDescriptorMethods,
    &descriptor_table_Protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SC_LOGIN_PACKET::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> SC_LOGIN_PACKET::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::SC_LOGIN_PACKET>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata SC_LOGIN_PACKET::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SC_ADD_PACKET::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SC_ADD_PACKET>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SC_ADD_PACKET, _impl_._has_bits_);
};

void SC_ADD_PACKET::clear_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pos_ != nullptr) _impl_.pos_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
SC_ADD_PACKET::SC_ADD_PACKET(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.SC_ADD_PACKET)
}
inline PROTOBUF_NDEBUG_INLINE SC_ADD_PACKET::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Protocol::SC_ADD_PACKET& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

SC_ADD_PACKET::SC_ADD_PACKET(
    ::google::protobuf::Arena* arena,
    const SC_ADD_PACKET& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SC_ADD_PACKET* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.pos_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::Protocol::Vec3>(
                              arena, *from._impl_.pos_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:Protocol.SC_ADD_PACKET)
}
inline PROTOBUF_NDEBUG_INLINE SC_ADD_PACKET::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SC_ADD_PACKET::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.pos_ = {};
}
SC_ADD_PACKET::~SC_ADD_PACKET() {
  // @@protoc_insertion_point(destructor:Protocol.SC_ADD_PACKET)
  SharedDtor(*this);
}
inline void SC_ADD_PACKET::SharedDtor(MessageLite& self) {
  SC_ADD_PACKET& this_ = static_cast<SC_ADD_PACKET&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.pos_;
  this_._impl_.~Impl_();
}

inline void* SC_ADD_PACKET::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SC_ADD_PACKET(arena);
}
constexpr auto SC_ADD_PACKET::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SC_ADD_PACKET),
                                            alignof(SC_ADD_PACKET));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SC_ADD_PACKET::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SC_ADD_PACKET_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SC_ADD_PACKET::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SC_ADD_PACKET>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SC_ADD_PACKET::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SC_ADD_PACKET>(), &SC_ADD_PACKET::ByteSizeLong,
            &SC_ADD_PACKET::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SC_ADD_PACKET, _impl_._cached_size_),
        false,
    },
    &SC_ADD_PACKET::kDescriptorMethods,
    &descriptor_table_Protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SC_ADD_PACKET::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> SC_ADD_PACKET::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SC_ADD_PACKET, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::SC_ADD_PACKET>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .Protocol.Vec3 pos = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(SC_ADD_PACKET, _impl_.pos_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Protocol.Vec3 pos = 1;
    {PROTOBUF_FIELD_OFFSET(SC_ADD_PACKET, _impl_.pos_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Protocol::Vec3>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void SC_ADD_PACKET::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.SC_ADD_PACKET)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.pos_ != nullptr);
    _impl_.pos_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SC_ADD_PACKET::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SC_ADD_PACKET& this_ = static_cast<const SC_ADD_PACKET&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SC_ADD_PACKET::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SC_ADD_PACKET& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.SC_ADD_PACKET)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .Protocol.Vec3 pos = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.pos_, this_._impl_.pos_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.SC_ADD_PACKET)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SC_ADD_PACKET::ByteSizeLong(const MessageLite& base) {
          const SC_ADD_PACKET& this_ = static_cast<const SC_ADD_PACKET&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SC_ADD_PACKET::ByteSizeLong() const {
          const SC_ADD_PACKET& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.SC_ADD_PACKET)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .Protocol.Vec3 pos = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.pos_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SC_ADD_PACKET::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SC_ADD_PACKET*>(&to_msg);
  auto& from = static_cast<const SC_ADD_PACKET&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.SC_ADD_PACKET)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.pos_ != nullptr);
    if (_this->_impl_.pos_ == nullptr) {
      _this->_impl_.pos_ =
          ::google::protobuf::Message::CopyConstruct<::Protocol::Vec3>(arena, *from._impl_.pos_);
    } else {
      _this->_impl_.pos_->MergeFrom(*from._impl_.pos_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SC_ADD_PACKET::CopyFrom(const SC_ADD_PACKET& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.SC_ADD_PACKET)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SC_ADD_PACKET::InternalSwap(SC_ADD_PACKET* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.pos_, other->_impl_.pos_);
}

::google::protobuf::Metadata SC_ADD_PACKET::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SC_MOVE_PACKET::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SC_MOVE_PACKET>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SC_MOVE_PACKET, _impl_._has_bits_);
};

void SC_MOVE_PACKET::clear_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pos_ != nullptr) _impl_.pos_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
SC_MOVE_PACKET::SC_MOVE_PACKET(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.SC_MOVE_PACKET)
}
inline PROTOBUF_NDEBUG_INLINE SC_MOVE_PACKET::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Protocol::SC_MOVE_PACKET& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

SC_MOVE_PACKET::SC_MOVE_PACKET(
    ::google::protobuf::Arena* arena,
    const SC_MOVE_PACKET& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SC_MOVE_PACKET* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.pos_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::Protocol::Vec3>(
                              arena, *from._impl_.pos_)
                        : nullptr;
  _impl_.rot_ = from._impl_.rot_;

  // @@protoc_insertion_point(copy_constructor:Protocol.SC_MOVE_PACKET)
}
inline PROTOBUF_NDEBUG_INLINE SC_MOVE_PACKET::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SC_MOVE_PACKET::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pos_),
           0,
           offsetof(Impl_, rot_) -
               offsetof(Impl_, pos_) +
               sizeof(Impl_::rot_));
}
SC_MOVE_PACKET::~SC_MOVE_PACKET() {
  // @@protoc_insertion_point(destructor:Protocol.SC_MOVE_PACKET)
  SharedDtor(*this);
}
inline void SC_MOVE_PACKET::SharedDtor(MessageLite& self) {
  SC_MOVE_PACKET& this_ = static_cast<SC_MOVE_PACKET&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.pos_;
  this_._impl_.~Impl_();
}

inline void* SC_MOVE_PACKET::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SC_MOVE_PACKET(arena);
}
constexpr auto SC_MOVE_PACKET::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SC_MOVE_PACKET),
                                            alignof(SC_MOVE_PACKET));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SC_MOVE_PACKET::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SC_MOVE_PACKET_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SC_MOVE_PACKET::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SC_MOVE_PACKET>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SC_MOVE_PACKET::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SC_MOVE_PACKET>(), &SC_MOVE_PACKET::ByteSizeLong,
            &SC_MOVE_PACKET::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SC_MOVE_PACKET, _impl_._cached_size_),
        false,
    },
    &SC_MOVE_PACKET::kDescriptorMethods,
    &descriptor_table_Protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SC_MOVE_PACKET::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> SC_MOVE_PACKET::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SC_MOVE_PACKET, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::SC_MOVE_PACKET>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float rot = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(SC_MOVE_PACKET, _impl_.rot_)}},
    // .Protocol.Vec3 pos = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(SC_MOVE_PACKET, _impl_.pos_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Protocol.Vec3 pos = 1;
    {PROTOBUF_FIELD_OFFSET(SC_MOVE_PACKET, _impl_.pos_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // float rot = 2;
    {PROTOBUF_FIELD_OFFSET(SC_MOVE_PACKET, _impl_.rot_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Protocol::Vec3>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void SC_MOVE_PACKET::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.SC_MOVE_PACKET)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.pos_ != nullptr);
    _impl_.pos_->Clear();
  }
  _impl_.rot_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SC_MOVE_PACKET::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SC_MOVE_PACKET& this_ = static_cast<const SC_MOVE_PACKET&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SC_MOVE_PACKET::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SC_MOVE_PACKET& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.SC_MOVE_PACKET)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .Protocol.Vec3 pos = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.pos_, this_._impl_.pos_->GetCachedSize(), target,
                stream);
          }

          // float rot = 2;
          if (::absl::bit_cast<::uint32_t>(this_._internal_rot()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_rot(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.SC_MOVE_PACKET)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SC_MOVE_PACKET::ByteSizeLong(const MessageLite& base) {
          const SC_MOVE_PACKET& this_ = static_cast<const SC_MOVE_PACKET&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SC_MOVE_PACKET::ByteSizeLong() const {
          const SC_MOVE_PACKET& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.SC_MOVE_PACKET)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .Protocol.Vec3 pos = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.pos_);
            }
          }
           {
            // float rot = 2;
            if (::absl::bit_cast<::uint32_t>(this_._internal_rot()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SC_MOVE_PACKET::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SC_MOVE_PACKET*>(&to_msg);
  auto& from = static_cast<const SC_MOVE_PACKET&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.SC_MOVE_PACKET)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.pos_ != nullptr);
    if (_this->_impl_.pos_ == nullptr) {
      _this->_impl_.pos_ =
          ::google::protobuf::Message::CopyConstruct<::Protocol::Vec3>(arena, *from._impl_.pos_);
    } else {
      _this->_impl_.pos_->MergeFrom(*from._impl_.pos_);
    }
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_rot()) != 0) {
    _this->_impl_.rot_ = from._impl_.rot_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SC_MOVE_PACKET::CopyFrom(const SC_MOVE_PACKET& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.SC_MOVE_PACKET)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SC_MOVE_PACKET::InternalSwap(SC_MOVE_PACKET* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SC_MOVE_PACKET, _impl_.rot_)
      + sizeof(SC_MOVE_PACKET::_impl_.rot_)
      - PROTOBUF_FIELD_OFFSET(SC_MOVE_PACKET, _impl_.pos_)>(
          reinterpret_cast<char*>(&_impl_.pos_),
          reinterpret_cast<char*>(&other->_impl_.pos_));
}

::google::protobuf::Metadata SC_MOVE_PACKET::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SC_REMOVE_PACKET::_Internal {
 public:
};

SC_REMOVE_PACKET::SC_REMOVE_PACKET(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:Protocol.SC_REMOVE_PACKET)
}
SC_REMOVE_PACKET::SC_REMOVE_PACKET(
    ::google::protobuf::Arena* arena,
    const SC_REMOVE_PACKET& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SC_REMOVE_PACKET* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Protocol.SC_REMOVE_PACKET)
}

inline void* SC_REMOVE_PACKET::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SC_REMOVE_PACKET(arena);
}
constexpr auto SC_REMOVE_PACKET::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SC_REMOVE_PACKET),
                                            alignof(SC_REMOVE_PACKET));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SC_REMOVE_PACKET::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SC_REMOVE_PACKET_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SC_REMOVE_PACKET::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<SC_REMOVE_PACKET>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SC_REMOVE_PACKET::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<SC_REMOVE_PACKET>(), &SC_REMOVE_PACKET::ByteSizeLong,
            &SC_REMOVE_PACKET::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SC_REMOVE_PACKET, _impl_._cached_size_),
        false,
    },
    &SC_REMOVE_PACKET::kDescriptorMethods,
    &descriptor_table_Protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SC_REMOVE_PACKET::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> SC_REMOVE_PACKET::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::SC_REMOVE_PACKET>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata SC_REMOVE_PACKET::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SC_ATTACK_PACKET::_Internal {
 public:
};

SC_ATTACK_PACKET::SC_ATTACK_PACKET(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.SC_ATTACK_PACKET)
}
SC_ATTACK_PACKET::SC_ATTACK_PACKET(
    ::google::protobuf::Arena* arena, const SC_ATTACK_PACKET& from)
    : SC_ATTACK_PACKET(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE SC_ATTACK_PACKET::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SC_ATTACK_PACKET::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.rot_ = {};
}
SC_ATTACK_PACKET::~SC_ATTACK_PACKET() {
  // @@protoc_insertion_point(destructor:Protocol.SC_ATTACK_PACKET)
  SharedDtor(*this);
}
inline void SC_ATTACK_PACKET::SharedDtor(MessageLite& self) {
  SC_ATTACK_PACKET& this_ = static_cast<SC_ATTACK_PACKET&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* SC_ATTACK_PACKET::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SC_ATTACK_PACKET(arena);
}
constexpr auto SC_ATTACK_PACKET::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SC_ATTACK_PACKET),
                                            alignof(SC_ATTACK_PACKET));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SC_ATTACK_PACKET::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SC_ATTACK_PACKET_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SC_ATTACK_PACKET::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SC_ATTACK_PACKET>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SC_ATTACK_PACKET::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SC_ATTACK_PACKET>(), &SC_ATTACK_PACKET::ByteSizeLong,
            &SC_ATTACK_PACKET::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SC_ATTACK_PACKET, _impl_._cached_size_),
        false,
    },
    &SC_ATTACK_PACKET::kDescriptorMethods,
    &descriptor_table_Protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SC_ATTACK_PACKET::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> SC_ATTACK_PACKET::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::SC_ATTACK_PACKET>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float rot = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(SC_ATTACK_PACKET, _impl_.rot_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float rot = 1;
    {PROTOBUF_FIELD_OFFSET(SC_ATTACK_PACKET, _impl_.rot_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void SC_ATTACK_PACKET::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.SC_ATTACK_PACKET)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.rot_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SC_ATTACK_PACKET::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SC_ATTACK_PACKET& this_ = static_cast<const SC_ATTACK_PACKET&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SC_ATTACK_PACKET::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SC_ATTACK_PACKET& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.SC_ATTACK_PACKET)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // float rot = 1;
          if (::absl::bit_cast<::uint32_t>(this_._internal_rot()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                1, this_._internal_rot(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.SC_ATTACK_PACKET)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SC_ATTACK_PACKET::ByteSizeLong(const MessageLite& base) {
          const SC_ATTACK_PACKET& this_ = static_cast<const SC_ATTACK_PACKET&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SC_ATTACK_PACKET::ByteSizeLong() const {
          const SC_ATTACK_PACKET& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.SC_ATTACK_PACKET)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // float rot = 1;
            if (::absl::bit_cast<::uint32_t>(this_._internal_rot()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SC_ATTACK_PACKET::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SC_ATTACK_PACKET*>(&to_msg);
  auto& from = static_cast<const SC_ATTACK_PACKET&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.SC_ATTACK_PACKET)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint32_t>(from._internal_rot()) != 0) {
    _this->_impl_.rot_ = from._impl_.rot_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SC_ATTACK_PACKET::CopyFrom(const SC_ATTACK_PACKET& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.SC_ATTACK_PACKET)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SC_ATTACK_PACKET::InternalSwap(SC_ATTACK_PACKET* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.rot_, other->_impl_.rot_);
}

::google::protobuf::Metadata SC_ATTACK_PACKET::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SC_DODGE_PACKET::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SC_DODGE_PACKET>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SC_DODGE_PACKET, _impl_._has_bits_);
};

void SC_DODGE_PACKET::clear_dir() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.dir_ != nullptr) _impl_.dir_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
SC_DODGE_PACKET::SC_DODGE_PACKET(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.SC_DODGE_PACKET)
}
inline PROTOBUF_NDEBUG_INLINE SC_DODGE_PACKET::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Protocol::SC_DODGE_PACKET& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

SC_DODGE_PACKET::SC_DODGE_PACKET(
    ::google::protobuf::Arena* arena,
    const SC_DODGE_PACKET& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SC_DODGE_PACKET* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.dir_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::Protocol::Vec3>(
                              arena, *from._impl_.dir_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:Protocol.SC_DODGE_PACKET)
}
inline PROTOBUF_NDEBUG_INLINE SC_DODGE_PACKET::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SC_DODGE_PACKET::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.dir_ = {};
}
SC_DODGE_PACKET::~SC_DODGE_PACKET() {
  // @@protoc_insertion_point(destructor:Protocol.SC_DODGE_PACKET)
  SharedDtor(*this);
}
inline void SC_DODGE_PACKET::SharedDtor(MessageLite& self) {
  SC_DODGE_PACKET& this_ = static_cast<SC_DODGE_PACKET&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.dir_;
  this_._impl_.~Impl_();
}

inline void* SC_DODGE_PACKET::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SC_DODGE_PACKET(arena);
}
constexpr auto SC_DODGE_PACKET::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SC_DODGE_PACKET),
                                            alignof(SC_DODGE_PACKET));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SC_DODGE_PACKET::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SC_DODGE_PACKET_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SC_DODGE_PACKET::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SC_DODGE_PACKET>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SC_DODGE_PACKET::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SC_DODGE_PACKET>(), &SC_DODGE_PACKET::ByteSizeLong,
            &SC_DODGE_PACKET::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SC_DODGE_PACKET, _impl_._cached_size_),
        false,
    },
    &SC_DODGE_PACKET::kDescriptorMethods,
    &descriptor_table_Protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SC_DODGE_PACKET::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> SC_DODGE_PACKET::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SC_DODGE_PACKET, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::SC_DODGE_PACKET>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .Protocol.Vec3 dir = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(SC_DODGE_PACKET, _impl_.dir_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Protocol.Vec3 dir = 1;
    {PROTOBUF_FIELD_OFFSET(SC_DODGE_PACKET, _impl_.dir_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Protocol::Vec3>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void SC_DODGE_PACKET::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.SC_DODGE_PACKET)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.dir_ != nullptr);
    _impl_.dir_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SC_DODGE_PACKET::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SC_DODGE_PACKET& this_ = static_cast<const SC_DODGE_PACKET&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SC_DODGE_PACKET::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SC_DODGE_PACKET& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.SC_DODGE_PACKET)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .Protocol.Vec3 dir = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.dir_, this_._impl_.dir_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.SC_DODGE_PACKET)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SC_DODGE_PACKET::ByteSizeLong(const MessageLite& base) {
          const SC_DODGE_PACKET& this_ = static_cast<const SC_DODGE_PACKET&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SC_DODGE_PACKET::ByteSizeLong() const {
          const SC_DODGE_PACKET& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.SC_DODGE_PACKET)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .Protocol.Vec3 dir = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.dir_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SC_DODGE_PACKET::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SC_DODGE_PACKET*>(&to_msg);
  auto& from = static_cast<const SC_DODGE_PACKET&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.SC_DODGE_PACKET)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.dir_ != nullptr);
    if (_this->_impl_.dir_ == nullptr) {
      _this->_impl_.dir_ =
          ::google::protobuf::Message::CopyConstruct<::Protocol::Vec3>(arena, *from._impl_.dir_);
    } else {
      _this->_impl_.dir_->MergeFrom(*from._impl_.dir_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SC_DODGE_PACKET::CopyFrom(const SC_DODGE_PACKET& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.SC_DODGE_PACKET)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SC_DODGE_PACKET::InternalSwap(SC_DODGE_PACKET* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.dir_, other->_impl_.dir_);
}

::google::protobuf::Metadata SC_DODGE_PACKET::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Protocol_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
