// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Protocol.proto
// Protobuf C++ Version: 5.29.5

#ifndef Protocol_2eproto_2epb_2eh
#define Protocol_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "Enum.pb.h"
#include "Struct.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Protocol_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocol_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Protocol_2eproto;
namespace Protocol {
class CS_INPUT_PACKET;
struct CS_INPUT_PACKETDefaultTypeInternal;
extern CS_INPUT_PACKETDefaultTypeInternal _CS_INPUT_PACKET_default_instance_;
class CS_LOGIN_PACKET;
struct CS_LOGIN_PACKETDefaultTypeInternal;
extern CS_LOGIN_PACKETDefaultTypeInternal _CS_LOGIN_PACKET_default_instance_;
class GamePacket;
struct GamePacketDefaultTypeInternal;
extern GamePacketDefaultTypeInternal _GamePacket_default_instance_;
class SC_ADD_PACKET;
struct SC_ADD_PACKETDefaultTypeInternal;
extern SC_ADD_PACKETDefaultTypeInternal _SC_ADD_PACKET_default_instance_;
class SC_ATTACK_PACKET;
struct SC_ATTACK_PACKETDefaultTypeInternal;
extern SC_ATTACK_PACKETDefaultTypeInternal _SC_ATTACK_PACKET_default_instance_;
class SC_DODGE_PACKET;
struct SC_DODGE_PACKETDefaultTypeInternal;
extern SC_DODGE_PACKETDefaultTypeInternal _SC_DODGE_PACKET_default_instance_;
class SC_LOGIN_PACKET;
struct SC_LOGIN_PACKETDefaultTypeInternal;
extern SC_LOGIN_PACKETDefaultTypeInternal _SC_LOGIN_PACKET_default_instance_;
class SC_MOVE_PACKET;
struct SC_MOVE_PACKETDefaultTypeInternal;
extern SC_MOVE_PACKETDefaultTypeInternal _SC_MOVE_PACKET_default_instance_;
class SC_REMOVE_PACKET;
struct SC_REMOVE_PACKETDefaultTypeInternal;
extern SC_REMOVE_PACKETDefaultTypeInternal _SC_REMOVE_PACKET_default_instance_;
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Protocol {

// ===================================================================


// -------------------------------------------------------------------

class SC_REMOVE_PACKET final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:Protocol.SC_REMOVE_PACKET) */ {
 public:
  inline SC_REMOVE_PACKET() : SC_REMOVE_PACKET(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SC_REMOVE_PACKET* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SC_REMOVE_PACKET));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SC_REMOVE_PACKET(
      ::google::protobuf::internal::ConstantInitialized);

  inline SC_REMOVE_PACKET(const SC_REMOVE_PACKET& from) : SC_REMOVE_PACKET(nullptr, from) {}
  inline SC_REMOVE_PACKET(SC_REMOVE_PACKET&& from) noexcept
      : SC_REMOVE_PACKET(nullptr, std::move(from)) {}
  inline SC_REMOVE_PACKET& operator=(const SC_REMOVE_PACKET& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_REMOVE_PACKET& operator=(SC_REMOVE_PACKET&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_REMOVE_PACKET& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_REMOVE_PACKET* internal_default_instance() {
    return reinterpret_cast<const SC_REMOVE_PACKET*>(
        &_SC_REMOVE_PACKET_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(SC_REMOVE_PACKET& a, SC_REMOVE_PACKET& b) { a.Swap(&b); }
  inline void Swap(SC_REMOVE_PACKET* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_REMOVE_PACKET* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_REMOVE_PACKET* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<SC_REMOVE_PACKET>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const SC_REMOVE_PACKET& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const SC_REMOVE_PACKET& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.SC_REMOVE_PACKET"; }

 protected:
  explicit SC_REMOVE_PACKET(::google::protobuf::Arena* arena);
  SC_REMOVE_PACKET(::google::protobuf::Arena* arena, const SC_REMOVE_PACKET& from);
  SC_REMOVE_PACKET(::google::protobuf::Arena* arena, SC_REMOVE_PACKET&& from) noexcept
      : SC_REMOVE_PACKET(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:Protocol.SC_REMOVE_PACKET)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SC_REMOVE_PACKET& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class SC_LOGIN_PACKET final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:Protocol.SC_LOGIN_PACKET) */ {
 public:
  inline SC_LOGIN_PACKET() : SC_LOGIN_PACKET(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SC_LOGIN_PACKET* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SC_LOGIN_PACKET));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SC_LOGIN_PACKET(
      ::google::protobuf::internal::ConstantInitialized);

  inline SC_LOGIN_PACKET(const SC_LOGIN_PACKET& from) : SC_LOGIN_PACKET(nullptr, from) {}
  inline SC_LOGIN_PACKET(SC_LOGIN_PACKET&& from) noexcept
      : SC_LOGIN_PACKET(nullptr, std::move(from)) {}
  inline SC_LOGIN_PACKET& operator=(const SC_LOGIN_PACKET& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_LOGIN_PACKET& operator=(SC_LOGIN_PACKET&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_LOGIN_PACKET& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_LOGIN_PACKET* internal_default_instance() {
    return reinterpret_cast<const SC_LOGIN_PACKET*>(
        &_SC_LOGIN_PACKET_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(SC_LOGIN_PACKET& a, SC_LOGIN_PACKET& b) { a.Swap(&b); }
  inline void Swap(SC_LOGIN_PACKET* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_LOGIN_PACKET* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_LOGIN_PACKET* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<SC_LOGIN_PACKET>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const SC_LOGIN_PACKET& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const SC_LOGIN_PACKET& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.SC_LOGIN_PACKET"; }

 protected:
  explicit SC_LOGIN_PACKET(::google::protobuf::Arena* arena);
  SC_LOGIN_PACKET(::google::protobuf::Arena* arena, const SC_LOGIN_PACKET& from);
  SC_LOGIN_PACKET(::google::protobuf::Arena* arena, SC_LOGIN_PACKET&& from) noexcept
      : SC_LOGIN_PACKET(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:Protocol.SC_LOGIN_PACKET)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SC_LOGIN_PACKET& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class SC_ATTACK_PACKET final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.SC_ATTACK_PACKET) */ {
 public:
  inline SC_ATTACK_PACKET() : SC_ATTACK_PACKET(nullptr) {}
  ~SC_ATTACK_PACKET() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SC_ATTACK_PACKET* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SC_ATTACK_PACKET));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SC_ATTACK_PACKET(
      ::google::protobuf::internal::ConstantInitialized);

  inline SC_ATTACK_PACKET(const SC_ATTACK_PACKET& from) : SC_ATTACK_PACKET(nullptr, from) {}
  inline SC_ATTACK_PACKET(SC_ATTACK_PACKET&& from) noexcept
      : SC_ATTACK_PACKET(nullptr, std::move(from)) {}
  inline SC_ATTACK_PACKET& operator=(const SC_ATTACK_PACKET& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_ATTACK_PACKET& operator=(SC_ATTACK_PACKET&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_ATTACK_PACKET& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_ATTACK_PACKET* internal_default_instance() {
    return reinterpret_cast<const SC_ATTACK_PACKET*>(
        &_SC_ATTACK_PACKET_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 7;
  friend void swap(SC_ATTACK_PACKET& a, SC_ATTACK_PACKET& b) { a.Swap(&b); }
  inline void Swap(SC_ATTACK_PACKET* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_ATTACK_PACKET* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_ATTACK_PACKET* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SC_ATTACK_PACKET>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SC_ATTACK_PACKET& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SC_ATTACK_PACKET& from) { SC_ATTACK_PACKET::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SC_ATTACK_PACKET* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.SC_ATTACK_PACKET"; }

 protected:
  explicit SC_ATTACK_PACKET(::google::protobuf::Arena* arena);
  SC_ATTACK_PACKET(::google::protobuf::Arena* arena, const SC_ATTACK_PACKET& from);
  SC_ATTACK_PACKET(::google::protobuf::Arena* arena, SC_ATTACK_PACKET&& from) noexcept
      : SC_ATTACK_PACKET(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRotFieldNumber = 1,
  };
  // float rot = 1;
  void clear_rot() ;
  float rot() const;
  void set_rot(float value);

  private:
  float _internal_rot() const;
  void _internal_set_rot(float value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.SC_ATTACK_PACKET)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SC_ATTACK_PACKET& from_msg);
    float rot_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class CS_LOGIN_PACKET final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:Protocol.CS_LOGIN_PACKET) */ {
 public:
  inline CS_LOGIN_PACKET() : CS_LOGIN_PACKET(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CS_LOGIN_PACKET* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CS_LOGIN_PACKET));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CS_LOGIN_PACKET(
      ::google::protobuf::internal::ConstantInitialized);

  inline CS_LOGIN_PACKET(const CS_LOGIN_PACKET& from) : CS_LOGIN_PACKET(nullptr, from) {}
  inline CS_LOGIN_PACKET(CS_LOGIN_PACKET&& from) noexcept
      : CS_LOGIN_PACKET(nullptr, std::move(from)) {}
  inline CS_LOGIN_PACKET& operator=(const CS_LOGIN_PACKET& from) {
    CopyFrom(from);
    return *this;
  }
  inline CS_LOGIN_PACKET& operator=(CS_LOGIN_PACKET&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CS_LOGIN_PACKET& default_instance() {
    return *internal_default_instance();
  }
  static inline const CS_LOGIN_PACKET* internal_default_instance() {
    return reinterpret_cast<const CS_LOGIN_PACKET*>(
        &_CS_LOGIN_PACKET_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CS_LOGIN_PACKET& a, CS_LOGIN_PACKET& b) { a.Swap(&b); }
  inline void Swap(CS_LOGIN_PACKET* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CS_LOGIN_PACKET* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CS_LOGIN_PACKET* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<CS_LOGIN_PACKET>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const CS_LOGIN_PACKET& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const CS_LOGIN_PACKET& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.CS_LOGIN_PACKET"; }

 protected:
  explicit CS_LOGIN_PACKET(::google::protobuf::Arena* arena);
  CS_LOGIN_PACKET(::google::protobuf::Arena* arena, const CS_LOGIN_PACKET& from);
  CS_LOGIN_PACKET(::google::protobuf::Arena* arena, CS_LOGIN_PACKET&& from) noexcept
      : CS_LOGIN_PACKET(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:Protocol.CS_LOGIN_PACKET)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const CS_LOGIN_PACKET& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class SC_MOVE_PACKET final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.SC_MOVE_PACKET) */ {
 public:
  inline SC_MOVE_PACKET() : SC_MOVE_PACKET(nullptr) {}
  ~SC_MOVE_PACKET() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SC_MOVE_PACKET* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SC_MOVE_PACKET));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SC_MOVE_PACKET(
      ::google::protobuf::internal::ConstantInitialized);

  inline SC_MOVE_PACKET(const SC_MOVE_PACKET& from) : SC_MOVE_PACKET(nullptr, from) {}
  inline SC_MOVE_PACKET(SC_MOVE_PACKET&& from) noexcept
      : SC_MOVE_PACKET(nullptr, std::move(from)) {}
  inline SC_MOVE_PACKET& operator=(const SC_MOVE_PACKET& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_MOVE_PACKET& operator=(SC_MOVE_PACKET&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_MOVE_PACKET& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_MOVE_PACKET* internal_default_instance() {
    return reinterpret_cast<const SC_MOVE_PACKET*>(
        &_SC_MOVE_PACKET_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(SC_MOVE_PACKET& a, SC_MOVE_PACKET& b) { a.Swap(&b); }
  inline void Swap(SC_MOVE_PACKET* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_MOVE_PACKET* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_MOVE_PACKET* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SC_MOVE_PACKET>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SC_MOVE_PACKET& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SC_MOVE_PACKET& from) { SC_MOVE_PACKET::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SC_MOVE_PACKET* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.SC_MOVE_PACKET"; }

 protected:
  explicit SC_MOVE_PACKET(::google::protobuf::Arena* arena);
  SC_MOVE_PACKET(::google::protobuf::Arena* arena, const SC_MOVE_PACKET& from);
  SC_MOVE_PACKET(::google::protobuf::Arena* arena, SC_MOVE_PACKET&& from) noexcept
      : SC_MOVE_PACKET(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPosFieldNumber = 1,
    kRotFieldNumber = 2,
  };
  // .Protocol.Vec3 pos = 1;
  bool has_pos() const;
  void clear_pos() ;
  const ::Protocol::Vec3& pos() const;
  PROTOBUF_NODISCARD ::Protocol::Vec3* release_pos();
  ::Protocol::Vec3* mutable_pos();
  void set_allocated_pos(::Protocol::Vec3* value);
  void unsafe_arena_set_allocated_pos(::Protocol::Vec3* value);
  ::Protocol::Vec3* unsafe_arena_release_pos();

  private:
  const ::Protocol::Vec3& _internal_pos() const;
  ::Protocol::Vec3* _internal_mutable_pos();

  public:
  // float rot = 2;
  void clear_rot() ;
  float rot() const;
  void set_rot(float value);

  private:
  float _internal_rot() const;
  void _internal_set_rot(float value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.SC_MOVE_PACKET)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SC_MOVE_PACKET& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::Protocol::Vec3* pos_;
    float rot_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class SC_DODGE_PACKET final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.SC_DODGE_PACKET) */ {
 public:
  inline SC_DODGE_PACKET() : SC_DODGE_PACKET(nullptr) {}
  ~SC_DODGE_PACKET() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SC_DODGE_PACKET* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SC_DODGE_PACKET));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SC_DODGE_PACKET(
      ::google::protobuf::internal::ConstantInitialized);

  inline SC_DODGE_PACKET(const SC_DODGE_PACKET& from) : SC_DODGE_PACKET(nullptr, from) {}
  inline SC_DODGE_PACKET(SC_DODGE_PACKET&& from) noexcept
      : SC_DODGE_PACKET(nullptr, std::move(from)) {}
  inline SC_DODGE_PACKET& operator=(const SC_DODGE_PACKET& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_DODGE_PACKET& operator=(SC_DODGE_PACKET&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_DODGE_PACKET& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_DODGE_PACKET* internal_default_instance() {
    return reinterpret_cast<const SC_DODGE_PACKET*>(
        &_SC_DODGE_PACKET_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 8;
  friend void swap(SC_DODGE_PACKET& a, SC_DODGE_PACKET& b) { a.Swap(&b); }
  inline void Swap(SC_DODGE_PACKET* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_DODGE_PACKET* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_DODGE_PACKET* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SC_DODGE_PACKET>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SC_DODGE_PACKET& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SC_DODGE_PACKET& from) { SC_DODGE_PACKET::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SC_DODGE_PACKET* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.SC_DODGE_PACKET"; }

 protected:
  explicit SC_DODGE_PACKET(::google::protobuf::Arena* arena);
  SC_DODGE_PACKET(::google::protobuf::Arena* arena, const SC_DODGE_PACKET& from);
  SC_DODGE_PACKET(::google::protobuf::Arena* arena, SC_DODGE_PACKET&& from) noexcept
      : SC_DODGE_PACKET(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDirFieldNumber = 1,
  };
  // .Protocol.Vec3 dir = 1;
  bool has_dir() const;
  void clear_dir() ;
  const ::Protocol::Vec3& dir() const;
  PROTOBUF_NODISCARD ::Protocol::Vec3* release_dir();
  ::Protocol::Vec3* mutable_dir();
  void set_allocated_dir(::Protocol::Vec3* value);
  void unsafe_arena_set_allocated_dir(::Protocol::Vec3* value);
  ::Protocol::Vec3* unsafe_arena_release_dir();

  private:
  const ::Protocol::Vec3& _internal_dir() const;
  ::Protocol::Vec3* _internal_mutable_dir();

  public:
  // @@protoc_insertion_point(class_scope:Protocol.SC_DODGE_PACKET)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SC_DODGE_PACKET& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::Protocol::Vec3* dir_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class SC_ADD_PACKET final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.SC_ADD_PACKET) */ {
 public:
  inline SC_ADD_PACKET() : SC_ADD_PACKET(nullptr) {}
  ~SC_ADD_PACKET() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SC_ADD_PACKET* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SC_ADD_PACKET));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SC_ADD_PACKET(
      ::google::protobuf::internal::ConstantInitialized);

  inline SC_ADD_PACKET(const SC_ADD_PACKET& from) : SC_ADD_PACKET(nullptr, from) {}
  inline SC_ADD_PACKET(SC_ADD_PACKET&& from) noexcept
      : SC_ADD_PACKET(nullptr, std::move(from)) {}
  inline SC_ADD_PACKET& operator=(const SC_ADD_PACKET& from) {
    CopyFrom(from);
    return *this;
  }
  inline SC_ADD_PACKET& operator=(SC_ADD_PACKET&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SC_ADD_PACKET& default_instance() {
    return *internal_default_instance();
  }
  static inline const SC_ADD_PACKET* internal_default_instance() {
    return reinterpret_cast<const SC_ADD_PACKET*>(
        &_SC_ADD_PACKET_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(SC_ADD_PACKET& a, SC_ADD_PACKET& b) { a.Swap(&b); }
  inline void Swap(SC_ADD_PACKET* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SC_ADD_PACKET* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SC_ADD_PACKET* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SC_ADD_PACKET>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SC_ADD_PACKET& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SC_ADD_PACKET& from) { SC_ADD_PACKET::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SC_ADD_PACKET* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.SC_ADD_PACKET"; }

 protected:
  explicit SC_ADD_PACKET(::google::protobuf::Arena* arena);
  SC_ADD_PACKET(::google::protobuf::Arena* arena, const SC_ADD_PACKET& from);
  SC_ADD_PACKET(::google::protobuf::Arena* arena, SC_ADD_PACKET&& from) noexcept
      : SC_ADD_PACKET(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPosFieldNumber = 1,
  };
  // .Protocol.Vec3 pos = 1;
  bool has_pos() const;
  void clear_pos() ;
  const ::Protocol::Vec3& pos() const;
  PROTOBUF_NODISCARD ::Protocol::Vec3* release_pos();
  ::Protocol::Vec3* mutable_pos();
  void set_allocated_pos(::Protocol::Vec3* value);
  void unsafe_arena_set_allocated_pos(::Protocol::Vec3* value);
  ::Protocol::Vec3* unsafe_arena_release_pos();

  private:
  const ::Protocol::Vec3& _internal_pos() const;
  ::Protocol::Vec3* _internal_mutable_pos();

  public:
  // @@protoc_insertion_point(class_scope:Protocol.SC_ADD_PACKET)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SC_ADD_PACKET& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::Protocol::Vec3* pos_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class GamePacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.GamePacket) */ {
 public:
  inline GamePacket() : GamePacket(nullptr) {}
  ~GamePacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GamePacket* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GamePacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GamePacket(
      ::google::protobuf::internal::ConstantInitialized);

  inline GamePacket(const GamePacket& from) : GamePacket(nullptr, from) {}
  inline GamePacket(GamePacket&& from) noexcept
      : GamePacket(nullptr, std::move(from)) {}
  inline GamePacket& operator=(const GamePacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline GamePacket& operator=(GamePacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GamePacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const GamePacket* internal_default_instance() {
    return reinterpret_cast<const GamePacket*>(
        &_GamePacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(GamePacket& a, GamePacket& b) { a.Swap(&b); }
  inline void Swap(GamePacket* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GamePacket* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GamePacket* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GamePacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GamePacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GamePacket& from) { GamePacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GamePacket* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.GamePacket"; }

 protected:
  explicit GamePacket(::google::protobuf::Arena* arena);
  GamePacket(::google::protobuf::Arena* arena, const GamePacket& from);
  GamePacket(::google::protobuf::Arena* arena, GamePacket&& from) noexcept
      : GamePacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBodyFieldNumber = 2,
    kHeaderFieldNumber = 1,
  };
  // bytes body = 2;
  void clear_body() ;
  const std::string& body() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_body(Arg_&& arg, Args_... args);
  std::string* mutable_body();
  PROTOBUF_NODISCARD std::string* release_body();
  void set_allocated_body(std::string* value);

  private:
  const std::string& _internal_body() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_body(
      const std::string& value);
  std::string* _internal_mutable_body();

  public:
  // .Protocol.PacketHeader header = 1;
  bool has_header() const;
  void clear_header() ;
  const ::Protocol::PacketHeader& header() const;
  PROTOBUF_NODISCARD ::Protocol::PacketHeader* release_header();
  ::Protocol::PacketHeader* mutable_header();
  void set_allocated_header(::Protocol::PacketHeader* value);
  void unsafe_arena_set_allocated_header(::Protocol::PacketHeader* value);
  ::Protocol::PacketHeader* unsafe_arena_release_header();

  private:
  const ::Protocol::PacketHeader& _internal_header() const;
  ::Protocol::PacketHeader* _internal_mutable_header();

  public:
  // @@protoc_insertion_point(class_scope:Protocol.GamePacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GamePacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr body_;
    ::Protocol::PacketHeader* header_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};
// -------------------------------------------------------------------

class CS_INPUT_PACKET final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.CS_INPUT_PACKET) */ {
 public:
  inline CS_INPUT_PACKET() : CS_INPUT_PACKET(nullptr) {}
  ~CS_INPUT_PACKET() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CS_INPUT_PACKET* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CS_INPUT_PACKET));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CS_INPUT_PACKET(
      ::google::protobuf::internal::ConstantInitialized);

  inline CS_INPUT_PACKET(const CS_INPUT_PACKET& from) : CS_INPUT_PACKET(nullptr, from) {}
  inline CS_INPUT_PACKET(CS_INPUT_PACKET&& from) noexcept
      : CS_INPUT_PACKET(nullptr, std::move(from)) {}
  inline CS_INPUT_PACKET& operator=(const CS_INPUT_PACKET& from) {
    CopyFrom(from);
    return *this;
  }
  inline CS_INPUT_PACKET& operator=(CS_INPUT_PACKET&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CS_INPUT_PACKET& default_instance() {
    return *internal_default_instance();
  }
  static inline const CS_INPUT_PACKET* internal_default_instance() {
    return reinterpret_cast<const CS_INPUT_PACKET*>(
        &_CS_INPUT_PACKET_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(CS_INPUT_PACKET& a, CS_INPUT_PACKET& b) { a.Swap(&b); }
  inline void Swap(CS_INPUT_PACKET* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CS_INPUT_PACKET* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CS_INPUT_PACKET* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CS_INPUT_PACKET>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CS_INPUT_PACKET& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CS_INPUT_PACKET& from) { CS_INPUT_PACKET::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CS_INPUT_PACKET* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.CS_INPUT_PACKET"; }

 protected:
  explicit CS_INPUT_PACKET(::google::protobuf::Arena* arena);
  CS_INPUT_PACKET(::google::protobuf::Arena* arena, const CS_INPUT_PACKET& from);
  CS_INPUT_PACKET(::google::protobuf::Arena* arena, CS_INPUT_PACKET&& from) noexcept
      : CS_INPUT_PACKET(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPayloadFieldNumber = 2,
    kKeyFieldNumber = 1,
  };
  // .Protocol.InputPayload payload = 2;
  bool has_payload() const;
  void clear_payload() ;
  const ::Protocol::InputPayload& payload() const;
  PROTOBUF_NODISCARD ::Protocol::InputPayload* release_payload();
  ::Protocol::InputPayload* mutable_payload();
  void set_allocated_payload(::Protocol::InputPayload* value);
  void unsafe_arena_set_allocated_payload(::Protocol::InputPayload* value);
  ::Protocol::InputPayload* unsafe_arena_release_payload();

  private:
  const ::Protocol::InputPayload& _internal_payload() const;
  ::Protocol::InputPayload* _internal_mutable_payload();

  public:
  // .Protocol.Input key = 1;
  void clear_key() ;
  ::Protocol::Input key() const;
  void set_key(::Protocol::Input value);

  private:
  ::Protocol::Input _internal_key() const;
  void _internal_set_key(::Protocol::Input value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.CS_INPUT_PACKET)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const CS_INPUT_PACKET& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::Protocol::InputPayload* payload_;
    int key_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GamePacket

// .Protocol.PacketHeader header = 1;
inline bool GamePacket::has_header() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.header_ != nullptr);
  return value;
}
inline const ::Protocol::PacketHeader& GamePacket::_internal_header() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Protocol::PacketHeader* p = _impl_.header_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::PacketHeader&>(::Protocol::_PacketHeader_default_instance_);
}
inline const ::Protocol::PacketHeader& GamePacket::header() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.GamePacket.header)
  return _internal_header();
}
inline void GamePacket::unsafe_arena_set_allocated_header(::Protocol::PacketHeader* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.header_);
  }
  _impl_.header_ = reinterpret_cast<::Protocol::PacketHeader*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.GamePacket.header)
}
inline ::Protocol::PacketHeader* GamePacket::release_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Protocol::PacketHeader* released = _impl_.header_;
  _impl_.header_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Protocol::PacketHeader* GamePacket::unsafe_arena_release_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.GamePacket.header)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Protocol::PacketHeader* temp = _impl_.header_;
  _impl_.header_ = nullptr;
  return temp;
}
inline ::Protocol::PacketHeader* GamePacket::_internal_mutable_header() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.header_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Protocol::PacketHeader>(GetArena());
    _impl_.header_ = reinterpret_cast<::Protocol::PacketHeader*>(p);
  }
  return _impl_.header_;
}
inline ::Protocol::PacketHeader* GamePacket::mutable_header() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Protocol::PacketHeader* _msg = _internal_mutable_header();
  // @@protoc_insertion_point(field_mutable:Protocol.GamePacket.header)
  return _msg;
}
inline void GamePacket::set_allocated_header(::Protocol::PacketHeader* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.header_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.header_ = reinterpret_cast<::Protocol::PacketHeader*>(value);
  // @@protoc_insertion_point(field_set_allocated:Protocol.GamePacket.header)
}

// bytes body = 2;
inline void GamePacket::clear_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.body_.ClearToEmpty();
}
inline const std::string& GamePacket::body() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.GamePacket.body)
  return _internal_body();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void GamePacket::set_body(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.body_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.GamePacket.body)
}
inline std::string* GamePacket::mutable_body() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_body();
  // @@protoc_insertion_point(field_mutable:Protocol.GamePacket.body)
  return _s;
}
inline const std::string& GamePacket::_internal_body() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.body_.Get();
}
inline void GamePacket::_internal_set_body(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.body_.Set(value, GetArena());
}
inline std::string* GamePacket::_internal_mutable_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.body_.Mutable( GetArena());
}
inline std::string* GamePacket::release_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.GamePacket.body)
  return _impl_.body_.Release();
}
inline void GamePacket::set_allocated_body(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.body_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.body_.IsDefault()) {
    _impl_.body_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.GamePacket.body)
}

// -------------------------------------------------------------------

// CS_LOGIN_PACKET

// -------------------------------------------------------------------

// CS_INPUT_PACKET

// .Protocol.Input key = 1;
inline void CS_INPUT_PACKET::clear_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.key_ = 0;
}
inline ::Protocol::Input CS_INPUT_PACKET::key() const {
  // @@protoc_insertion_point(field_get:Protocol.CS_INPUT_PACKET.key)
  return _internal_key();
}
inline void CS_INPUT_PACKET::set_key(::Protocol::Input value) {
  _internal_set_key(value);
  // @@protoc_insertion_point(field_set:Protocol.CS_INPUT_PACKET.key)
}
inline ::Protocol::Input CS_INPUT_PACKET::_internal_key() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::Input>(_impl_.key_);
}
inline void CS_INPUT_PACKET::_internal_set_key(::Protocol::Input value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.key_ = value;
}

// .Protocol.InputPayload payload = 2;
inline bool CS_INPUT_PACKET::has_payload() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.payload_ != nullptr);
  return value;
}
inline const ::Protocol::InputPayload& CS_INPUT_PACKET::_internal_payload() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Protocol::InputPayload* p = _impl_.payload_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::InputPayload&>(::Protocol::_InputPayload_default_instance_);
}
inline const ::Protocol::InputPayload& CS_INPUT_PACKET::payload() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.CS_INPUT_PACKET.payload)
  return _internal_payload();
}
inline void CS_INPUT_PACKET::unsafe_arena_set_allocated_payload(::Protocol::InputPayload* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.payload_);
  }
  _impl_.payload_ = reinterpret_cast<::Protocol::InputPayload*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.CS_INPUT_PACKET.payload)
}
inline ::Protocol::InputPayload* CS_INPUT_PACKET::release_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Protocol::InputPayload* released = _impl_.payload_;
  _impl_.payload_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Protocol::InputPayload* CS_INPUT_PACKET::unsafe_arena_release_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.CS_INPUT_PACKET.payload)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Protocol::InputPayload* temp = _impl_.payload_;
  _impl_.payload_ = nullptr;
  return temp;
}
inline ::Protocol::InputPayload* CS_INPUT_PACKET::_internal_mutable_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.payload_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Protocol::InputPayload>(GetArena());
    _impl_.payload_ = reinterpret_cast<::Protocol::InputPayload*>(p);
  }
  return _impl_.payload_;
}
inline ::Protocol::InputPayload* CS_INPUT_PACKET::mutable_payload() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Protocol::InputPayload* _msg = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:Protocol.CS_INPUT_PACKET.payload)
  return _msg;
}
inline void CS_INPUT_PACKET::set_allocated_payload(::Protocol::InputPayload* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.payload_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.payload_ = reinterpret_cast<::Protocol::InputPayload*>(value);
  // @@protoc_insertion_point(field_set_allocated:Protocol.CS_INPUT_PACKET.payload)
}

// -------------------------------------------------------------------

// SC_LOGIN_PACKET

// -------------------------------------------------------------------

// SC_ADD_PACKET

// .Protocol.Vec3 pos = 1;
inline bool SC_ADD_PACKET::has_pos() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.pos_ != nullptr);
  return value;
}
inline const ::Protocol::Vec3& SC_ADD_PACKET::_internal_pos() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Protocol::Vec3* p = _impl_.pos_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vec3&>(::Protocol::_Vec3_default_instance_);
}
inline const ::Protocol::Vec3& SC_ADD_PACKET::pos() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.SC_ADD_PACKET.pos)
  return _internal_pos();
}
inline void SC_ADD_PACKET::unsafe_arena_set_allocated_pos(::Protocol::Vec3* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.pos_);
  }
  _impl_.pos_ = reinterpret_cast<::Protocol::Vec3*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.SC_ADD_PACKET.pos)
}
inline ::Protocol::Vec3* SC_ADD_PACKET::release_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Protocol::Vec3* released = _impl_.pos_;
  _impl_.pos_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Protocol::Vec3* SC_ADD_PACKET::unsafe_arena_release_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.SC_ADD_PACKET.pos)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Protocol::Vec3* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
  return temp;
}
inline ::Protocol::Vec3* SC_ADD_PACKET::_internal_mutable_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pos_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Protocol::Vec3>(GetArena());
    _impl_.pos_ = reinterpret_cast<::Protocol::Vec3*>(p);
  }
  return _impl_.pos_;
}
inline ::Protocol::Vec3* SC_ADD_PACKET::mutable_pos() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Protocol::Vec3* _msg = _internal_mutable_pos();
  // @@protoc_insertion_point(field_mutable:Protocol.SC_ADD_PACKET.pos)
  return _msg;
}
inline void SC_ADD_PACKET::set_allocated_pos(::Protocol::Vec3* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.pos_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.pos_ = reinterpret_cast<::Protocol::Vec3*>(value);
  // @@protoc_insertion_point(field_set_allocated:Protocol.SC_ADD_PACKET.pos)
}

// -------------------------------------------------------------------

// SC_MOVE_PACKET

// .Protocol.Vec3 pos = 1;
inline bool SC_MOVE_PACKET::has_pos() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.pos_ != nullptr);
  return value;
}
inline const ::Protocol::Vec3& SC_MOVE_PACKET::_internal_pos() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Protocol::Vec3* p = _impl_.pos_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vec3&>(::Protocol::_Vec3_default_instance_);
}
inline const ::Protocol::Vec3& SC_MOVE_PACKET::pos() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.SC_MOVE_PACKET.pos)
  return _internal_pos();
}
inline void SC_MOVE_PACKET::unsafe_arena_set_allocated_pos(::Protocol::Vec3* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.pos_);
  }
  _impl_.pos_ = reinterpret_cast<::Protocol::Vec3*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.SC_MOVE_PACKET.pos)
}
inline ::Protocol::Vec3* SC_MOVE_PACKET::release_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Protocol::Vec3* released = _impl_.pos_;
  _impl_.pos_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Protocol::Vec3* SC_MOVE_PACKET::unsafe_arena_release_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.SC_MOVE_PACKET.pos)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Protocol::Vec3* temp = _impl_.pos_;
  _impl_.pos_ = nullptr;
  return temp;
}
inline ::Protocol::Vec3* SC_MOVE_PACKET::_internal_mutable_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.pos_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Protocol::Vec3>(GetArena());
    _impl_.pos_ = reinterpret_cast<::Protocol::Vec3*>(p);
  }
  return _impl_.pos_;
}
inline ::Protocol::Vec3* SC_MOVE_PACKET::mutable_pos() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Protocol::Vec3* _msg = _internal_mutable_pos();
  // @@protoc_insertion_point(field_mutable:Protocol.SC_MOVE_PACKET.pos)
  return _msg;
}
inline void SC_MOVE_PACKET::set_allocated_pos(::Protocol::Vec3* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.pos_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.pos_ = reinterpret_cast<::Protocol::Vec3*>(value);
  // @@protoc_insertion_point(field_set_allocated:Protocol.SC_MOVE_PACKET.pos)
}

// float rot = 2;
inline void SC_MOVE_PACKET::clear_rot() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rot_ = 0;
}
inline float SC_MOVE_PACKET::rot() const {
  // @@protoc_insertion_point(field_get:Protocol.SC_MOVE_PACKET.rot)
  return _internal_rot();
}
inline void SC_MOVE_PACKET::set_rot(float value) {
  _internal_set_rot(value);
  // @@protoc_insertion_point(field_set:Protocol.SC_MOVE_PACKET.rot)
}
inline float SC_MOVE_PACKET::_internal_rot() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rot_;
}
inline void SC_MOVE_PACKET::_internal_set_rot(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rot_ = value;
}

// -------------------------------------------------------------------

// SC_REMOVE_PACKET

// -------------------------------------------------------------------

// SC_ATTACK_PACKET

// float rot = 1;
inline void SC_ATTACK_PACKET::clear_rot() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rot_ = 0;
}
inline float SC_ATTACK_PACKET::rot() const {
  // @@protoc_insertion_point(field_get:Protocol.SC_ATTACK_PACKET.rot)
  return _internal_rot();
}
inline void SC_ATTACK_PACKET::set_rot(float value) {
  _internal_set_rot(value);
  // @@protoc_insertion_point(field_set:Protocol.SC_ATTACK_PACKET.rot)
}
inline float SC_ATTACK_PACKET::_internal_rot() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rot_;
}
inline void SC_ATTACK_PACKET::_internal_set_rot(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rot_ = value;
}

// -------------------------------------------------------------------

// SC_DODGE_PACKET

// .Protocol.Vec3 dir = 1;
inline bool SC_DODGE_PACKET::has_dir() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.dir_ != nullptr);
  return value;
}
inline const ::Protocol::Vec3& SC_DODGE_PACKET::_internal_dir() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::Protocol::Vec3* p = _impl_.dir_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vec3&>(::Protocol::_Vec3_default_instance_);
}
inline const ::Protocol::Vec3& SC_DODGE_PACKET::dir() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.SC_DODGE_PACKET.dir)
  return _internal_dir();
}
inline void SC_DODGE_PACKET::unsafe_arena_set_allocated_dir(::Protocol::Vec3* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.dir_);
  }
  _impl_.dir_ = reinterpret_cast<::Protocol::Vec3*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.SC_DODGE_PACKET.dir)
}
inline ::Protocol::Vec3* SC_DODGE_PACKET::release_dir() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Protocol::Vec3* released = _impl_.dir_;
  _impl_.dir_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::Protocol::Vec3* SC_DODGE_PACKET::unsafe_arena_release_dir() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.SC_DODGE_PACKET.dir)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::Protocol::Vec3* temp = _impl_.dir_;
  _impl_.dir_ = nullptr;
  return temp;
}
inline ::Protocol::Vec3* SC_DODGE_PACKET::_internal_mutable_dir() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.dir_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::Protocol::Vec3>(GetArena());
    _impl_.dir_ = reinterpret_cast<::Protocol::Vec3*>(p);
  }
  return _impl_.dir_;
}
inline ::Protocol::Vec3* SC_DODGE_PACKET::mutable_dir() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::Protocol::Vec3* _msg = _internal_mutable_dir();
  // @@protoc_insertion_point(field_mutable:Protocol.SC_DODGE_PACKET.dir)
  return _msg;
}
inline void SC_DODGE_PACKET::set_allocated_dir(::Protocol::Vec3* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.dir_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.dir_ = reinterpret_cast<::Protocol::Vec3*>(value);
  // @@protoc_insertion_point(field_set_allocated:Protocol.SC_DODGE_PACKET.dir)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Protocol_2eproto_2epb_2eh
