// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Struct.proto
// Protobuf C++ Version: 5.29.5

#include "Struct.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Protocol {

inline constexpr Vec3::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : x_{0},
        y_{0},
        z_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Vec3::Vec3(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Vec3DefaultTypeInternal {
  PROTOBUF_CONSTEXPR Vec3DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Vec3DefaultTypeInternal() {}
  union {
    Vec3 _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Vec3DefaultTypeInternal _Vec3_default_instance_;

inline constexpr PacketHeader::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : type_{static_cast< ::Protocol::PacketType >(0)},
        sessionid_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PacketHeader::PacketHeader(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PacketHeaderDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PacketHeaderDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PacketHeaderDefaultTypeInternal() {}
  union {
    PacketHeader _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PacketHeaderDefaultTypeInternal _PacketHeader_default_instance_;

inline constexpr MovePayload::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : front_{false},
        back_{false},
        right_{false},
        left_{false},
        campitch_{0},
        camyaw_{0},
        isrun_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MovePayload::MovePayload(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MovePayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MovePayloadDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MovePayloadDefaultTypeInternal() {}
  union {
    MovePayload _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MovePayloadDefaultTypeInternal _MovePayload_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR DodgePayload::DodgePayload(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct DodgePayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DodgePayloadDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DodgePayloadDefaultTypeInternal() {}
  union {
    DodgePayload _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DodgePayloadDefaultTypeInternal _DodgePayload_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR AttackPayload::AttackPayload(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct AttackPayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AttackPayloadDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AttackPayloadDefaultTypeInternal() {}
  union {
    AttackPayload _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AttackPayloadDefaultTypeInternal _AttackPayload_default_instance_;

inline constexpr InputPayload::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR InputPayload::InputPayload(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct InputPayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InputPayloadDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InputPayloadDefaultTypeInternal() {}
  union {
    InputPayload _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InputPayloadDefaultTypeInternal _InputPayload_default_instance_;
}  // namespace Protocol
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Struct_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Struct_2eproto = nullptr;
const ::uint32_t
    TableStruct_Struct_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::PacketHeader, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::PacketHeader, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::Protocol::PacketHeader, _impl_.sessionid_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::Vec3, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::Vec3, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::Protocol::Vec3, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::Protocol::Vec3, _impl_.z_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::InputPayload, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::Protocol::InputPayload, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::Protocol::InputPayload, _impl_.payload_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::MovePayload, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::MovePayload, _impl_.front_),
        PROTOBUF_FIELD_OFFSET(::Protocol::MovePayload, _impl_.back_),
        PROTOBUF_FIELD_OFFSET(::Protocol::MovePayload, _impl_.right_),
        PROTOBUF_FIELD_OFFSET(::Protocol::MovePayload, _impl_.left_),
        PROTOBUF_FIELD_OFFSET(::Protocol::MovePayload, _impl_.campitch_),
        PROTOBUF_FIELD_OFFSET(::Protocol::MovePayload, _impl_.camyaw_),
        PROTOBUF_FIELD_OFFSET(::Protocol::MovePayload, _impl_.isrun_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::AttackPayload, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::DodgePayload, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Protocol::PacketHeader)},
        {10, -1, -1, sizeof(::Protocol::Vec3)},
        {21, -1, -1, sizeof(::Protocol::InputPayload)},
        {33, -1, -1, sizeof(::Protocol::MovePayload)},
        {48, -1, -1, sizeof(::Protocol::AttackPayload)},
        {56, -1, -1, sizeof(::Protocol::DodgePayload)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::Protocol::_PacketHeader_default_instance_._instance,
    &::Protocol::_Vec3_default_instance_._instance,
    &::Protocol::_InputPayload_default_instance_._instance,
    &::Protocol::_MovePayload_default_instance_._instance,
    &::Protocol::_AttackPayload_default_instance_._instance,
    &::Protocol::_DodgePayload_default_instance_._instance,
};
const char descriptor_table_protodef_Struct_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014Struct.proto\022\010Protocol\032\nEnum.proto\"E\n\014"
    "PacketHeader\022\"\n\004type\030\001 \001(\0162\024.Protocol.Pa"
    "cketType\022\021\n\tsessionId\030\002 \001(\005\"\'\n\004Vec3\022\t\n\001x"
    "\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\"\224\001\n\014InputPa"
    "yload\022%\n\004move\030\001 \001(\0132\025.Protocol.MovePaylo"
    "adH\000\022)\n\006attack\030\002 \001(\0132\027.Protocol.AttackPa"
    "yloadH\000\022\'\n\005dodge\030\003 \001(\0132\026.Protocol.DodgeP"
    "ayloadH\000B\t\n\007payload\"x\n\013MovePayload\022\r\n\005fr"
    "ont\030\001 \001(\010\022\014\n\004back\030\002 \001(\010\022\r\n\005right\030\003 \001(\010\022\014"
    "\n\004left\030\004 \001(\010\022\020\n\010camPitch\030\005 \001(\002\022\016\n\006camYaw"
    "\030\006 \001(\002\022\r\n\005isRun\030\007 \001(\010\"\017\n\rAttackPayload\"\016"
    "\n\014DodgePayloadb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_Struct_2eproto_deps[1] =
    {
        &::descriptor_table_Enum_2eproto,
};
static ::absl::once_flag descriptor_table_Struct_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Struct_2eproto = {
    false,
    false,
    462,
    descriptor_table_protodef_Struct_2eproto,
    "Struct.proto",
    &descriptor_table_Struct_2eproto_once,
    descriptor_table_Struct_2eproto_deps,
    1,
    6,
    schemas,
    file_default_instances,
    TableStruct_Struct_2eproto::offsets,
    file_level_enum_descriptors_Struct_2eproto,
    file_level_service_descriptors_Struct_2eproto,
};
namespace Protocol {
// ===================================================================

class PacketHeader::_Internal {
 public:
};

PacketHeader::PacketHeader(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.PacketHeader)
}
PacketHeader::PacketHeader(
    ::google::protobuf::Arena* arena, const PacketHeader& from)
    : PacketHeader(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE PacketHeader::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void PacketHeader::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           0,
           offsetof(Impl_, sessionid_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::sessionid_));
}
PacketHeader::~PacketHeader() {
  // @@protoc_insertion_point(destructor:Protocol.PacketHeader)
  SharedDtor(*this);
}
inline void PacketHeader::SharedDtor(MessageLite& self) {
  PacketHeader& this_ = static_cast<PacketHeader&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PacketHeader::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PacketHeader(arena);
}
constexpr auto PacketHeader::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PacketHeader),
                                            alignof(PacketHeader));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PacketHeader::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PacketHeader_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PacketHeader::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PacketHeader>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PacketHeader::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PacketHeader>(), &PacketHeader::ByteSizeLong,
            &PacketHeader::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_._cached_size_),
        false,
    },
    &PacketHeader::kDescriptorMethods,
    &descriptor_table_Struct_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PacketHeader::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> PacketHeader::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::PacketHeader>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 sessionId = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PacketHeader, _impl_.sessionid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.sessionid_)}},
    // .Protocol.PacketType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PacketHeader, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.type_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Protocol.PacketType type = 1;
    {PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // int32 sessionId = 2;
    {PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.sessionid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void PacketHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.PacketHeader)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.type_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.sessionid_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.sessionid_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PacketHeader::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PacketHeader& this_ = static_cast<const PacketHeader&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PacketHeader::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PacketHeader& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.PacketHeader)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .Protocol.PacketType type = 1;
          if (this_._internal_type() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_type(), target);
          }

          // int32 sessionId = 2;
          if (this_._internal_sessionid() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_sessionid(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.PacketHeader)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PacketHeader::ByteSizeLong(const MessageLite& base) {
          const PacketHeader& this_ = static_cast<const PacketHeader&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PacketHeader::ByteSizeLong() const {
          const PacketHeader& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.PacketHeader)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .Protocol.PacketType type = 1;
            if (this_._internal_type() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
            }
            // int32 sessionId = 2;
            if (this_._internal_sessionid() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_sessionid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PacketHeader::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PacketHeader*>(&to_msg);
  auto& from = static_cast<const PacketHeader&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.PacketHeader)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_type() != 0) {
    _this->_impl_.type_ = from._impl_.type_;
  }
  if (from._internal_sessionid() != 0) {
    _this->_impl_.sessionid_ = from._impl_.sessionid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PacketHeader::CopyFrom(const PacketHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.PacketHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PacketHeader::InternalSwap(PacketHeader* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.sessionid_)
      + sizeof(PacketHeader::_impl_.sessionid_)
      - PROTOBUF_FIELD_OFFSET(PacketHeader, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::google::protobuf::Metadata PacketHeader::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Vec3::_Internal {
 public:
};

Vec3::Vec3(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.Vec3)
}
Vec3::Vec3(
    ::google::protobuf::Arena* arena, const Vec3& from)
    : Vec3(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Vec3::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Vec3::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, z_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::z_));
}
Vec3::~Vec3() {
  // @@protoc_insertion_point(destructor:Protocol.Vec3)
  SharedDtor(*this);
}
inline void Vec3::SharedDtor(MessageLite& self) {
  Vec3& this_ = static_cast<Vec3&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Vec3::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Vec3(arena);
}
constexpr auto Vec3::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Vec3),
                                            alignof(Vec3));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Vec3::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Vec3_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Vec3::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Vec3>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Vec3::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Vec3>(), &Vec3::ByteSizeLong,
            &Vec3::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Vec3, _impl_._cached_size_),
        false,
    },
    &Vec3::kDescriptorMethods,
    &descriptor_table_Struct_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Vec3::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> Vec3::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::Vec3>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // float x = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(Vec3, _impl_.x_)}},
    // float y = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(Vec3, _impl_.y_)}},
    // float z = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(Vec3, _impl_.z_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float x = 1;
    {PROTOBUF_FIELD_OFFSET(Vec3, _impl_.x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float y = 2;
    {PROTOBUF_FIELD_OFFSET(Vec3, _impl_.y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float z = 3;
    {PROTOBUF_FIELD_OFFSET(Vec3, _impl_.z_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Vec3::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.Vec3)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.z_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Vec3::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Vec3& this_ = static_cast<const Vec3&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Vec3::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Vec3& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.Vec3)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // float x = 1;
          if (::absl::bit_cast<::uint32_t>(this_._internal_x()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                1, this_._internal_x(), target);
          }

          // float y = 2;
          if (::absl::bit_cast<::uint32_t>(this_._internal_y()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_y(), target);
          }

          // float z = 3;
          if (::absl::bit_cast<::uint32_t>(this_._internal_z()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                3, this_._internal_z(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.Vec3)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Vec3::ByteSizeLong(const MessageLite& base) {
          const Vec3& this_ = static_cast<const Vec3&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Vec3::ByteSizeLong() const {
          const Vec3& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.Vec3)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // float x = 1;
            if (::absl::bit_cast<::uint32_t>(this_._internal_x()) != 0) {
              total_size += 5;
            }
            // float y = 2;
            if (::absl::bit_cast<::uint32_t>(this_._internal_y()) != 0) {
              total_size += 5;
            }
            // float z = 3;
            if (::absl::bit_cast<::uint32_t>(this_._internal_z()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Vec3::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Vec3*>(&to_msg);
  auto& from = static_cast<const Vec3&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.Vec3)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint32_t>(from._internal_x()) != 0) {
    _this->_impl_.x_ = from._impl_.x_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_y()) != 0) {
    _this->_impl_.y_ = from._impl_.y_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_z()) != 0) {
    _this->_impl_.z_ = from._impl_.z_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Vec3::CopyFrom(const Vec3& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.Vec3)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Vec3::InternalSwap(Vec3* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Vec3, _impl_.z_)
      + sizeof(Vec3::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(Vec3, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata Vec3::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class InputPayload::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::Protocol::InputPayload, _impl_._oneof_case_);
};

void InputPayload::set_allocated_move(::Protocol::MovePayload* move) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (move) {
    ::google::protobuf::Arena* submessage_arena = move->GetArena();
    if (message_arena != submessage_arena) {
      move = ::google::protobuf::internal::GetOwnedMessage(message_arena, move, submessage_arena);
    }
    set_has_move();
    _impl_.payload_.move_ = move;
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.InputPayload.move)
}
void InputPayload::set_allocated_attack(::Protocol::AttackPayload* attack) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (attack) {
    ::google::protobuf::Arena* submessage_arena = attack->GetArena();
    if (message_arena != submessage_arena) {
      attack = ::google::protobuf::internal::GetOwnedMessage(message_arena, attack, submessage_arena);
    }
    set_has_attack();
    _impl_.payload_.attack_ = attack;
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.InputPayload.attack)
}
void InputPayload::set_allocated_dodge(::Protocol::DodgePayload* dodge) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (dodge) {
    ::google::protobuf::Arena* submessage_arena = dodge->GetArena();
    if (message_arena != submessage_arena) {
      dodge = ::google::protobuf::internal::GetOwnedMessage(message_arena, dodge, submessage_arena);
    }
    set_has_dodge();
    _impl_.payload_.dodge_ = dodge;
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.InputPayload.dodge)
}
InputPayload::InputPayload(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.InputPayload)
}
inline PROTOBUF_NDEBUG_INLINE InputPayload::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Protocol::InputPayload& from_msg)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

InputPayload::InputPayload(
    ::google::protobuf::Arena* arena,
    const InputPayload& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  InputPayload* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (payload_case()) {
    case PAYLOAD_NOT_SET:
      break;
      case kMove:
        _impl_.payload_.move_ = ::google::protobuf::Message::CopyConstruct<::Protocol::MovePayload>(arena, *from._impl_.payload_.move_);
        break;
      case kAttack:
        _impl_.payload_.attack_ = ::google::protobuf::Message::CopyConstruct<::Protocol::AttackPayload>(arena, *from._impl_.payload_.attack_);
        break;
      case kDodge:
        _impl_.payload_.dodge_ = ::google::protobuf::Message::CopyConstruct<::Protocol::DodgePayload>(arena, *from._impl_.payload_.dodge_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:Protocol.InputPayload)
}
inline PROTOBUF_NDEBUG_INLINE InputPayload::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void InputPayload::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
InputPayload::~InputPayload() {
  // @@protoc_insertion_point(destructor:Protocol.InputPayload)
  SharedDtor(*this);
}
inline void InputPayload::SharedDtor(MessageLite& self) {
  InputPayload& this_ = static_cast<InputPayload&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_payload()) {
    this_.clear_payload();
  }
  this_._impl_.~Impl_();
}

void InputPayload::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:Protocol.InputPayload)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (payload_case()) {
    case kMove: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.move_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.move_);
      }
      break;
    }
    case kAttack: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.attack_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.attack_);
      }
      break;
    }
    case kDodge: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.dodge_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.dodge_);
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


inline void* InputPayload::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) InputPayload(arena);
}
constexpr auto InputPayload::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(InputPayload),
                                            alignof(InputPayload));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull InputPayload::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_InputPayload_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &InputPayload::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<InputPayload>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &InputPayload::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<InputPayload>(), &InputPayload::ByteSizeLong,
            &InputPayload::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(InputPayload, _impl_._cached_size_),
        false,
    },
    &InputPayload::kDescriptorMethods,
    &descriptor_table_Struct_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* InputPayload::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 3, 3, 0, 2> InputPayload::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::InputPayload>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .Protocol.MovePayload move = 1;
    {PROTOBUF_FIELD_OFFSET(InputPayload, _impl_.payload_.move_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Protocol.AttackPayload attack = 2;
    {PROTOBUF_FIELD_OFFSET(InputPayload, _impl_.payload_.attack_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .Protocol.DodgePayload dodge = 3;
    {PROTOBUF_FIELD_OFFSET(InputPayload, _impl_.payload_.dodge_), _Internal::kOneofCaseOffset + 0, 2,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Protocol::MovePayload>()},
    {::_pbi::TcParser::GetTable<::Protocol::AttackPayload>()},
    {::_pbi::TcParser::GetTable<::Protocol::DodgePayload>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void InputPayload::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.InputPayload)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_payload();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* InputPayload::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const InputPayload& this_ = static_cast<const InputPayload&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* InputPayload::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const InputPayload& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.InputPayload)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          switch (this_.payload_case()) {
            case kMove: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  1, *this_._impl_.payload_.move_, this_._impl_.payload_.move_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kAttack: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  2, *this_._impl_.payload_.attack_, this_._impl_.payload_.attack_->GetCachedSize(), target,
                  stream);
              break;
            }
            case kDodge: {
              target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                  3, *this_._impl_.payload_.dodge_, this_._impl_.payload_.dodge_->GetCachedSize(), target,
                  stream);
              break;
            }
            default:
              break;
          }
          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.InputPayload)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t InputPayload::ByteSizeLong(const MessageLite& base) {
          const InputPayload& this_ = static_cast<const InputPayload&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t InputPayload::ByteSizeLong() const {
          const InputPayload& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.InputPayload)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          switch (this_.payload_case()) {
            // .Protocol.MovePayload move = 1;
            case kMove: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.move_);
              break;
            }
            // .Protocol.AttackPayload attack = 2;
            case kAttack: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.attack_);
              break;
            }
            // .Protocol.DodgePayload dodge = 3;
            case kDodge: {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.dodge_);
              break;
            }
            case PAYLOAD_NOT_SET: {
              break;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void InputPayload::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<InputPayload*>(&to_msg);
  auto& from = static_cast<const InputPayload&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.InputPayload)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_payload();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kMove: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.move_ =
              ::google::protobuf::Message::CopyConstruct<::Protocol::MovePayload>(arena, *from._impl_.payload_.move_);
        } else {
          _this->_impl_.payload_.move_->MergeFrom(from._internal_move());
        }
        break;
      }
      case kAttack: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.attack_ =
              ::google::protobuf::Message::CopyConstruct<::Protocol::AttackPayload>(arena, *from._impl_.payload_.attack_);
        } else {
          _this->_impl_.payload_.attack_->MergeFrom(from._internal_attack());
        }
        break;
      }
      case kDodge: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.dodge_ =
              ::google::protobuf::Message::CopyConstruct<::Protocol::DodgePayload>(arena, *from._impl_.payload_.dodge_);
        } else {
          _this->_impl_.payload_.dodge_->MergeFrom(from._internal_dodge());
        }
        break;
      }
      case PAYLOAD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void InputPayload::CopyFrom(const InputPayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.InputPayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void InputPayload::InternalSwap(InputPayload* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata InputPayload::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MovePayload::_Internal {
 public:
};

MovePayload::MovePayload(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.MovePayload)
}
MovePayload::MovePayload(
    ::google::protobuf::Arena* arena, const MovePayload& from)
    : MovePayload(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE MovePayload::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void MovePayload::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, front_),
           0,
           offsetof(Impl_, isrun_) -
               offsetof(Impl_, front_) +
               sizeof(Impl_::isrun_));
}
MovePayload::~MovePayload() {
  // @@protoc_insertion_point(destructor:Protocol.MovePayload)
  SharedDtor(*this);
}
inline void MovePayload::SharedDtor(MessageLite& self) {
  MovePayload& this_ = static_cast<MovePayload&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* MovePayload::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) MovePayload(arena);
}
constexpr auto MovePayload::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(MovePayload),
                                            alignof(MovePayload));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull MovePayload::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_MovePayload_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &MovePayload::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<MovePayload>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &MovePayload::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<MovePayload>(), &MovePayload::ByteSizeLong,
            &MovePayload::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(MovePayload, _impl_._cached_size_),
        false,
    },
    &MovePayload::kDescriptorMethods,
    &descriptor_table_Struct_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* MovePayload::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 0, 2> MovePayload::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::MovePayload>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool front = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(MovePayload, _impl_.front_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MovePayload, _impl_.front_)}},
    // bool back = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(MovePayload, _impl_.back_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(MovePayload, _impl_.back_)}},
    // bool right = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(MovePayload, _impl_.right_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(MovePayload, _impl_.right_)}},
    // bool left = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(MovePayload, _impl_.left_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(MovePayload, _impl_.left_)}},
    // float camPitch = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 63, 0, PROTOBUF_FIELD_OFFSET(MovePayload, _impl_.campitch_)}},
    // float camYaw = 6;
    {::_pbi::TcParser::FastF32S1,
     {53, 63, 0, PROTOBUF_FIELD_OFFSET(MovePayload, _impl_.camyaw_)}},
    // bool isRun = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(MovePayload, _impl_.isrun_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(MovePayload, _impl_.isrun_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool front = 1;
    {PROTOBUF_FIELD_OFFSET(MovePayload, _impl_.front_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool back = 2;
    {PROTOBUF_FIELD_OFFSET(MovePayload, _impl_.back_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool right = 3;
    {PROTOBUF_FIELD_OFFSET(MovePayload, _impl_.right_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bool left = 4;
    {PROTOBUF_FIELD_OFFSET(MovePayload, _impl_.left_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // float camPitch = 5;
    {PROTOBUF_FIELD_OFFSET(MovePayload, _impl_.campitch_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float camYaw = 6;
    {PROTOBUF_FIELD_OFFSET(MovePayload, _impl_.camyaw_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // bool isRun = 7;
    {PROTOBUF_FIELD_OFFSET(MovePayload, _impl_.isrun_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void MovePayload::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.MovePayload)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.front_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.isrun_) -
      reinterpret_cast<char*>(&_impl_.front_)) + sizeof(_impl_.isrun_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* MovePayload::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const MovePayload& this_ = static_cast<const MovePayload&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* MovePayload::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const MovePayload& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.MovePayload)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool front = 1;
          if (this_._internal_front() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_front(), target);
          }

          // bool back = 2;
          if (this_._internal_back() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_back(), target);
          }

          // bool right = 3;
          if (this_._internal_right() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_right(), target);
          }

          // bool left = 4;
          if (this_._internal_left() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                4, this_._internal_left(), target);
          }

          // float camPitch = 5;
          if (::absl::bit_cast<::uint32_t>(this_._internal_campitch()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                5, this_._internal_campitch(), target);
          }

          // float camYaw = 6;
          if (::absl::bit_cast<::uint32_t>(this_._internal_camyaw()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                6, this_._internal_camyaw(), target);
          }

          // bool isRun = 7;
          if (this_._internal_isrun() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                7, this_._internal_isrun(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.MovePayload)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t MovePayload::ByteSizeLong(const MessageLite& base) {
          const MovePayload& this_ = static_cast<const MovePayload&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t MovePayload::ByteSizeLong() const {
          const MovePayload& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.MovePayload)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bool front = 1;
            if (this_._internal_front() != 0) {
              total_size += 2;
            }
            // bool back = 2;
            if (this_._internal_back() != 0) {
              total_size += 2;
            }
            // bool right = 3;
            if (this_._internal_right() != 0) {
              total_size += 2;
            }
            // bool left = 4;
            if (this_._internal_left() != 0) {
              total_size += 2;
            }
            // float camPitch = 5;
            if (::absl::bit_cast<::uint32_t>(this_._internal_campitch()) != 0) {
              total_size += 5;
            }
            // float camYaw = 6;
            if (::absl::bit_cast<::uint32_t>(this_._internal_camyaw()) != 0) {
              total_size += 5;
            }
            // bool isRun = 7;
            if (this_._internal_isrun() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void MovePayload::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MovePayload*>(&to_msg);
  auto& from = static_cast<const MovePayload&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.MovePayload)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_front() != 0) {
    _this->_impl_.front_ = from._impl_.front_;
  }
  if (from._internal_back() != 0) {
    _this->_impl_.back_ = from._impl_.back_;
  }
  if (from._internal_right() != 0) {
    _this->_impl_.right_ = from._impl_.right_;
  }
  if (from._internal_left() != 0) {
    _this->_impl_.left_ = from._impl_.left_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_campitch()) != 0) {
    _this->_impl_.campitch_ = from._impl_.campitch_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_camyaw()) != 0) {
    _this->_impl_.camyaw_ = from._impl_.camyaw_;
  }
  if (from._internal_isrun() != 0) {
    _this->_impl_.isrun_ = from._impl_.isrun_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MovePayload::CopyFrom(const MovePayload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.MovePayload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MovePayload::InternalSwap(MovePayload* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MovePayload, _impl_.isrun_)
      + sizeof(MovePayload::_impl_.isrun_)
      - PROTOBUF_FIELD_OFFSET(MovePayload, _impl_.front_)>(
          reinterpret_cast<char*>(&_impl_.front_),
          reinterpret_cast<char*>(&other->_impl_.front_));
}

::google::protobuf::Metadata MovePayload::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AttackPayload::_Internal {
 public:
};

AttackPayload::AttackPayload(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:Protocol.AttackPayload)
}
AttackPayload::AttackPayload(
    ::google::protobuf::Arena* arena,
    const AttackPayload& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AttackPayload* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Protocol.AttackPayload)
}

inline void* AttackPayload::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) AttackPayload(arena);
}
constexpr auto AttackPayload::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(AttackPayload),
                                            alignof(AttackPayload));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull AttackPayload::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_AttackPayload_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &AttackPayload::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<AttackPayload>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &AttackPayload::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<AttackPayload>(), &AttackPayload::ByteSizeLong,
            &AttackPayload::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(AttackPayload, _impl_._cached_size_),
        false,
    },
    &AttackPayload::kDescriptorMethods,
    &descriptor_table_Struct_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* AttackPayload::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> AttackPayload::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::AttackPayload>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata AttackPayload::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DodgePayload::_Internal {
 public:
};

DodgePayload::DodgePayload(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:Protocol.DodgePayload)
}
DodgePayload::DodgePayload(
    ::google::protobuf::Arena* arena,
    const DodgePayload& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DodgePayload* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:Protocol.DodgePayload)
}

inline void* DodgePayload::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DodgePayload(arena);
}
constexpr auto DodgePayload::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(DodgePayload),
                                            alignof(DodgePayload));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DodgePayload::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DodgePayload_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DodgePayload::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<DodgePayload>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DodgePayload::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<DodgePayload>(), &DodgePayload::ByteSizeLong,
            &DodgePayload::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DodgePayload, _impl_._cached_size_),
        false,
    },
    &DodgePayload::kDescriptorMethods,
    &descriptor_table_Struct_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DodgePayload::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> DodgePayload::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::DodgePayload>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata DodgePayload::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Struct_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
