// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Struct.proto
// Protobuf C++ Version: 5.29.5

#ifndef Struct_2eproto_2epb_2eh
#define Struct_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "Enum.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Struct_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Struct_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Struct_2eproto;
namespace Protocol {
class AttackPayload;
struct AttackPayloadDefaultTypeInternal;
extern AttackPayloadDefaultTypeInternal _AttackPayload_default_instance_;
class DodgePayload;
struct DodgePayloadDefaultTypeInternal;
extern DodgePayloadDefaultTypeInternal _DodgePayload_default_instance_;
class InputPayload;
struct InputPayloadDefaultTypeInternal;
extern InputPayloadDefaultTypeInternal _InputPayload_default_instance_;
class MovePayload;
struct MovePayloadDefaultTypeInternal;
extern MovePayloadDefaultTypeInternal _MovePayload_default_instance_;
class PacketHeader;
struct PacketHeaderDefaultTypeInternal;
extern PacketHeaderDefaultTypeInternal _PacketHeader_default_instance_;
class Vec3;
struct Vec3DefaultTypeInternal;
extern Vec3DefaultTypeInternal _Vec3_default_instance_;
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Protocol {

// ===================================================================


// -------------------------------------------------------------------

class Vec3 final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.Vec3) */ {
 public:
  inline Vec3() : Vec3(nullptr) {}
  ~Vec3() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Vec3* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Vec3));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Vec3(
      ::google::protobuf::internal::ConstantInitialized);

  inline Vec3(const Vec3& from) : Vec3(nullptr, from) {}
  inline Vec3(Vec3&& from) noexcept
      : Vec3(nullptr, std::move(from)) {}
  inline Vec3& operator=(const Vec3& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vec3& operator=(Vec3&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vec3& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vec3* internal_default_instance() {
    return reinterpret_cast<const Vec3*>(
        &_Vec3_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Vec3& a, Vec3& b) { a.Swap(&b); }
  inline void Swap(Vec3* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vec3* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vec3* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Vec3>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Vec3& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Vec3& from) { Vec3::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Vec3* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.Vec3"; }

 protected:
  explicit Vec3(::google::protobuf::Arena* arena);
  Vec3(::google::protobuf::Arena* arena, const Vec3& from);
  Vec3(::google::protobuf::Arena* arena, Vec3&& from) noexcept
      : Vec3(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 2;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // float z = 3;
  void clear_z() ;
  float z() const;
  void set_z(float value);

  private:
  float _internal_z() const;
  void _internal_set_z(float value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.Vec3)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Vec3& from_msg);
    float x_;
    float y_;
    float z_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class PacketHeader final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.PacketHeader) */ {
 public:
  inline PacketHeader() : PacketHeader(nullptr) {}
  ~PacketHeader() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PacketHeader* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PacketHeader));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PacketHeader(
      ::google::protobuf::internal::ConstantInitialized);

  inline PacketHeader(const PacketHeader& from) : PacketHeader(nullptr, from) {}
  inline PacketHeader(PacketHeader&& from) noexcept
      : PacketHeader(nullptr, std::move(from)) {}
  inline PacketHeader& operator=(const PacketHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline PacketHeader& operator=(PacketHeader&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PacketHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const PacketHeader* internal_default_instance() {
    return reinterpret_cast<const PacketHeader*>(
        &_PacketHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PacketHeader& a, PacketHeader& b) { a.Swap(&b); }
  inline void Swap(PacketHeader* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PacketHeader* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PacketHeader* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PacketHeader>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PacketHeader& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PacketHeader& from) { PacketHeader::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PacketHeader* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.PacketHeader"; }

 protected:
  explicit PacketHeader(::google::protobuf::Arena* arena);
  PacketHeader(::google::protobuf::Arena* arena, const PacketHeader& from);
  PacketHeader(::google::protobuf::Arena* arena, PacketHeader&& from) noexcept
      : PacketHeader(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTypeFieldNumber = 1,
    kSessionIdFieldNumber = 2,
  };
  // .Protocol.PacketType type = 1;
  void clear_type() ;
  ::Protocol::PacketType type() const;
  void set_type(::Protocol::PacketType value);

  private:
  ::Protocol::PacketType _internal_type() const;
  void _internal_set_type(::Protocol::PacketType value);

  public:
  // int32 sessionId = 2;
  void clear_sessionid() ;
  ::int32_t sessionid() const;
  void set_sessionid(::int32_t value);

  private:
  ::int32_t _internal_sessionid() const;
  void _internal_set_sessionid(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.PacketHeader)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PacketHeader& from_msg);
    int type_;
    ::int32_t sessionid_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class MovePayload final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.MovePayload) */ {
 public:
  inline MovePayload() : MovePayload(nullptr) {}
  ~MovePayload() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MovePayload* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MovePayload));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MovePayload(
      ::google::protobuf::internal::ConstantInitialized);

  inline MovePayload(const MovePayload& from) : MovePayload(nullptr, from) {}
  inline MovePayload(MovePayload&& from) noexcept
      : MovePayload(nullptr, std::move(from)) {}
  inline MovePayload& operator=(const MovePayload& from) {
    CopyFrom(from);
    return *this;
  }
  inline MovePayload& operator=(MovePayload&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MovePayload& default_instance() {
    return *internal_default_instance();
  }
  static inline const MovePayload* internal_default_instance() {
    return reinterpret_cast<const MovePayload*>(
        &_MovePayload_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(MovePayload& a, MovePayload& b) { a.Swap(&b); }
  inline void Swap(MovePayload* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MovePayload* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MovePayload* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MovePayload>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MovePayload& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MovePayload& from) { MovePayload::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MovePayload* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.MovePayload"; }

 protected:
  explicit MovePayload(::google::protobuf::Arena* arena);
  MovePayload(::google::protobuf::Arena* arena, const MovePayload& from);
  MovePayload(::google::protobuf::Arena* arena, MovePayload&& from) noexcept
      : MovePayload(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFrontFieldNumber = 1,
    kBackFieldNumber = 2,
    kRightFieldNumber = 3,
    kLeftFieldNumber = 4,
    kCamPitchFieldNumber = 5,
    kCamYawFieldNumber = 6,
    kIsRunFieldNumber = 7,
  };
  // bool front = 1;
  void clear_front() ;
  bool front() const;
  void set_front(bool value);

  private:
  bool _internal_front() const;
  void _internal_set_front(bool value);

  public:
  // bool back = 2;
  void clear_back() ;
  bool back() const;
  void set_back(bool value);

  private:
  bool _internal_back() const;
  void _internal_set_back(bool value);

  public:
  // bool right = 3;
  void clear_right() ;
  bool right() const;
  void set_right(bool value);

  private:
  bool _internal_right() const;
  void _internal_set_right(bool value);

  public:
  // bool left = 4;
  void clear_left() ;
  bool left() const;
  void set_left(bool value);

  private:
  bool _internal_left() const;
  void _internal_set_left(bool value);

  public:
  // float camPitch = 5;
  void clear_campitch() ;
  float campitch() const;
  void set_campitch(float value);

  private:
  float _internal_campitch() const;
  void _internal_set_campitch(float value);

  public:
  // float camYaw = 6;
  void clear_camyaw() ;
  float camyaw() const;
  void set_camyaw(float value);

  private:
  float _internal_camyaw() const;
  void _internal_set_camyaw(float value);

  public:
  // bool isRun = 7;
  void clear_isrun() ;
  bool isrun() const;
  void set_isrun(bool value);

  private:
  bool _internal_isrun() const;
  void _internal_set_isrun(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.MovePayload)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const MovePayload& from_msg);
    bool front_;
    bool back_;
    bool right_;
    bool left_;
    float campitch_;
    float camyaw_;
    bool isrun_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class DodgePayload final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:Protocol.DodgePayload) */ {
 public:
  inline DodgePayload() : DodgePayload(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DodgePayload* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DodgePayload));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DodgePayload(
      ::google::protobuf::internal::ConstantInitialized);

  inline DodgePayload(const DodgePayload& from) : DodgePayload(nullptr, from) {}
  inline DodgePayload(DodgePayload&& from) noexcept
      : DodgePayload(nullptr, std::move(from)) {}
  inline DodgePayload& operator=(const DodgePayload& from) {
    CopyFrom(from);
    return *this;
  }
  inline DodgePayload& operator=(DodgePayload&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DodgePayload& default_instance() {
    return *internal_default_instance();
  }
  static inline const DodgePayload* internal_default_instance() {
    return reinterpret_cast<const DodgePayload*>(
        &_DodgePayload_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(DodgePayload& a, DodgePayload& b) { a.Swap(&b); }
  inline void Swap(DodgePayload* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DodgePayload* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DodgePayload* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<DodgePayload>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const DodgePayload& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const DodgePayload& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.DodgePayload"; }

 protected:
  explicit DodgePayload(::google::protobuf::Arena* arena);
  DodgePayload(::google::protobuf::Arena* arena, const DodgePayload& from);
  DodgePayload(::google::protobuf::Arena* arena, DodgePayload&& from) noexcept
      : DodgePayload(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:Protocol.DodgePayload)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DodgePayload& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class AttackPayload final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:Protocol.AttackPayload) */ {
 public:
  inline AttackPayload() : AttackPayload(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AttackPayload* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AttackPayload));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AttackPayload(
      ::google::protobuf::internal::ConstantInitialized);

  inline AttackPayload(const AttackPayload& from) : AttackPayload(nullptr, from) {}
  inline AttackPayload(AttackPayload&& from) noexcept
      : AttackPayload(nullptr, std::move(from)) {}
  inline AttackPayload& operator=(const AttackPayload& from) {
    CopyFrom(from);
    return *this;
  }
  inline AttackPayload& operator=(AttackPayload&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AttackPayload& default_instance() {
    return *internal_default_instance();
  }
  static inline const AttackPayload* internal_default_instance() {
    return reinterpret_cast<const AttackPayload*>(
        &_AttackPayload_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(AttackPayload& a, AttackPayload& b) { a.Swap(&b); }
  inline void Swap(AttackPayload* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AttackPayload* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AttackPayload* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<AttackPayload>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const AttackPayload& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const AttackPayload& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.AttackPayload"; }

 protected:
  explicit AttackPayload(::google::protobuf::Arena* arena);
  AttackPayload(::google::protobuf::Arena* arena, const AttackPayload& from);
  AttackPayload(::google::protobuf::Arena* arena, AttackPayload&& from) noexcept
      : AttackPayload(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:Protocol.AttackPayload)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AttackPayload& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class InputPayload final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.InputPayload) */ {
 public:
  inline InputPayload() : InputPayload(nullptr) {}
  ~InputPayload() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(InputPayload* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(InputPayload));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR InputPayload(
      ::google::protobuf::internal::ConstantInitialized);

  inline InputPayload(const InputPayload& from) : InputPayload(nullptr, from) {}
  inline InputPayload(InputPayload&& from) noexcept
      : InputPayload(nullptr, std::move(from)) {}
  inline InputPayload& operator=(const InputPayload& from) {
    CopyFrom(from);
    return *this;
  }
  inline InputPayload& operator=(InputPayload&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InputPayload& default_instance() {
    return *internal_default_instance();
  }
  enum PayloadCase {
    kMove = 1,
    kAttack = 2,
    kDodge = 3,
    PAYLOAD_NOT_SET = 0,
  };
  static inline const InputPayload* internal_default_instance() {
    return reinterpret_cast<const InputPayload*>(
        &_InputPayload_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(InputPayload& a, InputPayload& b) { a.Swap(&b); }
  inline void Swap(InputPayload* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InputPayload* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InputPayload* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<InputPayload>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const InputPayload& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const InputPayload& from) { InputPayload::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(InputPayload* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.InputPayload"; }

 protected:
  explicit InputPayload(::google::protobuf::Arena* arena);
  InputPayload(::google::protobuf::Arena* arena, const InputPayload& from);
  InputPayload(::google::protobuf::Arena* arena, InputPayload&& from) noexcept
      : InputPayload(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMoveFieldNumber = 1,
    kAttackFieldNumber = 2,
    kDodgeFieldNumber = 3,
  };
  // .Protocol.MovePayload move = 1;
  bool has_move() const;
  private:
  bool _internal_has_move() const;

  public:
  void clear_move() ;
  const ::Protocol::MovePayload& move() const;
  PROTOBUF_NODISCARD ::Protocol::MovePayload* release_move();
  ::Protocol::MovePayload* mutable_move();
  void set_allocated_move(::Protocol::MovePayload* value);
  void unsafe_arena_set_allocated_move(::Protocol::MovePayload* value);
  ::Protocol::MovePayload* unsafe_arena_release_move();

  private:
  const ::Protocol::MovePayload& _internal_move() const;
  ::Protocol::MovePayload* _internal_mutable_move();

  public:
  // .Protocol.AttackPayload attack = 2;
  bool has_attack() const;
  private:
  bool _internal_has_attack() const;

  public:
  void clear_attack() ;
  const ::Protocol::AttackPayload& attack() const;
  PROTOBUF_NODISCARD ::Protocol::AttackPayload* release_attack();
  ::Protocol::AttackPayload* mutable_attack();
  void set_allocated_attack(::Protocol::AttackPayload* value);
  void unsafe_arena_set_allocated_attack(::Protocol::AttackPayload* value);
  ::Protocol::AttackPayload* unsafe_arena_release_attack();

  private:
  const ::Protocol::AttackPayload& _internal_attack() const;
  ::Protocol::AttackPayload* _internal_mutable_attack();

  public:
  // .Protocol.DodgePayload dodge = 3;
  bool has_dodge() const;
  private:
  bool _internal_has_dodge() const;

  public:
  void clear_dodge() ;
  const ::Protocol::DodgePayload& dodge() const;
  PROTOBUF_NODISCARD ::Protocol::DodgePayload* release_dodge();
  ::Protocol::DodgePayload* mutable_dodge();
  void set_allocated_dodge(::Protocol::DodgePayload* value);
  void unsafe_arena_set_allocated_dodge(::Protocol::DodgePayload* value);
  ::Protocol::DodgePayload* unsafe_arena_release_dodge();

  private:
  const ::Protocol::DodgePayload& _internal_dodge() const;
  ::Protocol::DodgePayload* _internal_mutable_dodge();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:Protocol.InputPayload)
 private:
  class _Internal;
  void set_has_move();
  void set_has_attack();
  void set_has_dodge();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 3, 3,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const InputPayload& from_msg);
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::Protocol::MovePayload* move_;
      ::Protocol::AttackPayload* attack_;
      ::Protocol::DodgePayload* dodge_;
    } payload_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PacketHeader

// .Protocol.PacketType type = 1;
inline void PacketHeader::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::Protocol::PacketType PacketHeader::type() const {
  // @@protoc_insertion_point(field_get:Protocol.PacketHeader.type)
  return _internal_type();
}
inline void PacketHeader::set_type(::Protocol::PacketType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:Protocol.PacketHeader.type)
}
inline ::Protocol::PacketType PacketHeader::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::PacketType>(_impl_.type_);
}
inline void PacketHeader::_internal_set_type(::Protocol::PacketType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// int32 sessionId = 2;
inline void PacketHeader::clear_sessionid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_ = 0;
}
inline ::int32_t PacketHeader::sessionid() const {
  // @@protoc_insertion_point(field_get:Protocol.PacketHeader.sessionId)
  return _internal_sessionid();
}
inline void PacketHeader::set_sessionid(::int32_t value) {
  _internal_set_sessionid(value);
  // @@protoc_insertion_point(field_set:Protocol.PacketHeader.sessionId)
}
inline ::int32_t PacketHeader::_internal_sessionid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sessionid_;
}
inline void PacketHeader::_internal_set_sessionid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sessionid_ = value;
}

// -------------------------------------------------------------------

// Vec3

// float x = 1;
inline void Vec3::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
}
inline float Vec3::x() const {
  // @@protoc_insertion_point(field_get:Protocol.Vec3.x)
  return _internal_x();
}
inline void Vec3::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Protocol.Vec3.x)
}
inline float Vec3::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void Vec3::_internal_set_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// float y = 2;
inline void Vec3::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
}
inline float Vec3::y() const {
  // @@protoc_insertion_point(field_get:Protocol.Vec3.y)
  return _internal_y();
}
inline void Vec3::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Protocol.Vec3.y)
}
inline float Vec3::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void Vec3::_internal_set_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// float z = 3;
inline void Vec3::clear_z() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = 0;
}
inline float Vec3::z() const {
  // @@protoc_insertion_point(field_get:Protocol.Vec3.z)
  return _internal_z();
}
inline void Vec3::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Protocol.Vec3.z)
}
inline float Vec3::_internal_z() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.z_;
}
inline void Vec3::_internal_set_z(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.z_ = value;
}

// -------------------------------------------------------------------

// InputPayload

// .Protocol.MovePayload move = 1;
inline bool InputPayload::has_move() const {
  return payload_case() == kMove;
}
inline bool InputPayload::_internal_has_move() const {
  return payload_case() == kMove;
}
inline void InputPayload::set_has_move() {
  _impl_._oneof_case_[0] = kMove;
}
inline void InputPayload::clear_move() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kMove) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.move_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.move_);
    }
    clear_has_payload();
  }
}
inline ::Protocol::MovePayload* InputPayload::release_move() {
  // @@protoc_insertion_point(field_release:Protocol.InputPayload.move)
  if (payload_case() == kMove) {
    clear_has_payload();
    auto* temp = _impl_.payload_.move_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.move_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Protocol::MovePayload& InputPayload::_internal_move() const {
  return payload_case() == kMove ? *_impl_.payload_.move_ : reinterpret_cast<::Protocol::MovePayload&>(::Protocol::_MovePayload_default_instance_);
}
inline const ::Protocol::MovePayload& InputPayload::move() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.InputPayload.move)
  return _internal_move();
}
inline ::Protocol::MovePayload* InputPayload::unsafe_arena_release_move() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Protocol.InputPayload.move)
  if (payload_case() == kMove) {
    clear_has_payload();
    auto* temp = _impl_.payload_.move_;
    _impl_.payload_.move_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void InputPayload::unsafe_arena_set_allocated_move(::Protocol::MovePayload* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_move();
    _impl_.payload_.move_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.InputPayload.move)
}
inline ::Protocol::MovePayload* InputPayload::_internal_mutable_move() {
  if (payload_case() != kMove) {
    clear_payload();
    set_has_move();
    _impl_.payload_.move_ =
        ::google::protobuf::Message::DefaultConstruct<::Protocol::MovePayload>(GetArena());
  }
  return _impl_.payload_.move_;
}
inline ::Protocol::MovePayload* InputPayload::mutable_move() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Protocol::MovePayload* _msg = _internal_mutable_move();
  // @@protoc_insertion_point(field_mutable:Protocol.InputPayload.move)
  return _msg;
}

// .Protocol.AttackPayload attack = 2;
inline bool InputPayload::has_attack() const {
  return payload_case() == kAttack;
}
inline bool InputPayload::_internal_has_attack() const {
  return payload_case() == kAttack;
}
inline void InputPayload::set_has_attack() {
  _impl_._oneof_case_[0] = kAttack;
}
inline void InputPayload::clear_attack() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kAttack) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.attack_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.attack_);
    }
    clear_has_payload();
  }
}
inline ::Protocol::AttackPayload* InputPayload::release_attack() {
  // @@protoc_insertion_point(field_release:Protocol.InputPayload.attack)
  if (payload_case() == kAttack) {
    clear_has_payload();
    auto* temp = _impl_.payload_.attack_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.attack_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Protocol::AttackPayload& InputPayload::_internal_attack() const {
  return payload_case() == kAttack ? *_impl_.payload_.attack_ : reinterpret_cast<::Protocol::AttackPayload&>(::Protocol::_AttackPayload_default_instance_);
}
inline const ::Protocol::AttackPayload& InputPayload::attack() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.InputPayload.attack)
  return _internal_attack();
}
inline ::Protocol::AttackPayload* InputPayload::unsafe_arena_release_attack() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Protocol.InputPayload.attack)
  if (payload_case() == kAttack) {
    clear_has_payload();
    auto* temp = _impl_.payload_.attack_;
    _impl_.payload_.attack_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void InputPayload::unsafe_arena_set_allocated_attack(::Protocol::AttackPayload* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_attack();
    _impl_.payload_.attack_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.InputPayload.attack)
}
inline ::Protocol::AttackPayload* InputPayload::_internal_mutable_attack() {
  if (payload_case() != kAttack) {
    clear_payload();
    set_has_attack();
    _impl_.payload_.attack_ =
        ::google::protobuf::Message::DefaultConstruct<::Protocol::AttackPayload>(GetArena());
  }
  return _impl_.payload_.attack_;
}
inline ::Protocol::AttackPayload* InputPayload::mutable_attack() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Protocol::AttackPayload* _msg = _internal_mutable_attack();
  // @@protoc_insertion_point(field_mutable:Protocol.InputPayload.attack)
  return _msg;
}

// .Protocol.DodgePayload dodge = 3;
inline bool InputPayload::has_dodge() const {
  return payload_case() == kDodge;
}
inline bool InputPayload::_internal_has_dodge() const {
  return payload_case() == kDodge;
}
inline void InputPayload::set_has_dodge() {
  _impl_._oneof_case_[0] = kDodge;
}
inline void InputPayload::clear_dodge() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kDodge) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.dodge_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.dodge_);
    }
    clear_has_payload();
  }
}
inline ::Protocol::DodgePayload* InputPayload::release_dodge() {
  // @@protoc_insertion_point(field_release:Protocol.InputPayload.dodge)
  if (payload_case() == kDodge) {
    clear_has_payload();
    auto* temp = _impl_.payload_.dodge_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.dodge_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Protocol::DodgePayload& InputPayload::_internal_dodge() const {
  return payload_case() == kDodge ? *_impl_.payload_.dodge_ : reinterpret_cast<::Protocol::DodgePayload&>(::Protocol::_DodgePayload_default_instance_);
}
inline const ::Protocol::DodgePayload& InputPayload::dodge() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.InputPayload.dodge)
  return _internal_dodge();
}
inline ::Protocol::DodgePayload* InputPayload::unsafe_arena_release_dodge() {
  // @@protoc_insertion_point(field_unsafe_arena_release:Protocol.InputPayload.dodge)
  if (payload_case() == kDodge) {
    clear_has_payload();
    auto* temp = _impl_.payload_.dodge_;
    _impl_.payload_.dodge_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void InputPayload::unsafe_arena_set_allocated_dodge(::Protocol::DodgePayload* value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_dodge();
    _impl_.payload_.dodge_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.InputPayload.dodge)
}
inline ::Protocol::DodgePayload* InputPayload::_internal_mutable_dodge() {
  if (payload_case() != kDodge) {
    clear_payload();
    set_has_dodge();
    _impl_.payload_.dodge_ =
        ::google::protobuf::Message::DefaultConstruct<::Protocol::DodgePayload>(GetArena());
  }
  return _impl_.payload_.dodge_;
}
inline ::Protocol::DodgePayload* InputPayload::mutable_dodge() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Protocol::DodgePayload* _msg = _internal_mutable_dodge();
  // @@protoc_insertion_point(field_mutable:Protocol.InputPayload.dodge)
  return _msg;
}

inline bool InputPayload::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void InputPayload::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline InputPayload::PayloadCase InputPayload::payload_case() const {
  return InputPayload::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// MovePayload

// bool front = 1;
inline void MovePayload::clear_front() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.front_ = false;
}
inline bool MovePayload::front() const {
  // @@protoc_insertion_point(field_get:Protocol.MovePayload.front)
  return _internal_front();
}
inline void MovePayload::set_front(bool value) {
  _internal_set_front(value);
  // @@protoc_insertion_point(field_set:Protocol.MovePayload.front)
}
inline bool MovePayload::_internal_front() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.front_;
}
inline void MovePayload::_internal_set_front(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.front_ = value;
}

// bool back = 2;
inline void MovePayload::clear_back() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.back_ = false;
}
inline bool MovePayload::back() const {
  // @@protoc_insertion_point(field_get:Protocol.MovePayload.back)
  return _internal_back();
}
inline void MovePayload::set_back(bool value) {
  _internal_set_back(value);
  // @@protoc_insertion_point(field_set:Protocol.MovePayload.back)
}
inline bool MovePayload::_internal_back() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.back_;
}
inline void MovePayload::_internal_set_back(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.back_ = value;
}

// bool right = 3;
inline void MovePayload::clear_right() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.right_ = false;
}
inline bool MovePayload::right() const {
  // @@protoc_insertion_point(field_get:Protocol.MovePayload.right)
  return _internal_right();
}
inline void MovePayload::set_right(bool value) {
  _internal_set_right(value);
  // @@protoc_insertion_point(field_set:Protocol.MovePayload.right)
}
inline bool MovePayload::_internal_right() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.right_;
}
inline void MovePayload::_internal_set_right(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.right_ = value;
}

// bool left = 4;
inline void MovePayload::clear_left() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.left_ = false;
}
inline bool MovePayload::left() const {
  // @@protoc_insertion_point(field_get:Protocol.MovePayload.left)
  return _internal_left();
}
inline void MovePayload::set_left(bool value) {
  _internal_set_left(value);
  // @@protoc_insertion_point(field_set:Protocol.MovePayload.left)
}
inline bool MovePayload::_internal_left() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.left_;
}
inline void MovePayload::_internal_set_left(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.left_ = value;
}

// float camPitch = 5;
inline void MovePayload::clear_campitch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.campitch_ = 0;
}
inline float MovePayload::campitch() const {
  // @@protoc_insertion_point(field_get:Protocol.MovePayload.camPitch)
  return _internal_campitch();
}
inline void MovePayload::set_campitch(float value) {
  _internal_set_campitch(value);
  // @@protoc_insertion_point(field_set:Protocol.MovePayload.camPitch)
}
inline float MovePayload::_internal_campitch() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.campitch_;
}
inline void MovePayload::_internal_set_campitch(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.campitch_ = value;
}

// float camYaw = 6;
inline void MovePayload::clear_camyaw() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.camyaw_ = 0;
}
inline float MovePayload::camyaw() const {
  // @@protoc_insertion_point(field_get:Protocol.MovePayload.camYaw)
  return _internal_camyaw();
}
inline void MovePayload::set_camyaw(float value) {
  _internal_set_camyaw(value);
  // @@protoc_insertion_point(field_set:Protocol.MovePayload.camYaw)
}
inline float MovePayload::_internal_camyaw() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.camyaw_;
}
inline void MovePayload::_internal_set_camyaw(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.camyaw_ = value;
}

// bool isRun = 7;
inline void MovePayload::clear_isrun() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isrun_ = false;
}
inline bool MovePayload::isrun() const {
  // @@protoc_insertion_point(field_get:Protocol.MovePayload.isRun)
  return _internal_isrun();
}
inline void MovePayload::set_isrun(bool value) {
  _internal_set_isrun(value);
  // @@protoc_insertion_point(field_set:Protocol.MovePayload.isRun)
}
inline bool MovePayload::_internal_isrun() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.isrun_;
}
inline void MovePayload::_internal_set_isrun(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isrun_ = value;
}

// -------------------------------------------------------------------

// AttackPayload

// -------------------------------------------------------------------

// DodgePayload

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Struct_2eproto_2epb_2eh
